### ISSUE TITLE
Deploy - K8S - Temporal fails with special characters on password

### ISSUE THREAD

**Issue by ordonezf** [airbytehq/airbyte#10106]
## Environment
- **Airbyte version**:  0.35.15-alpha
- **OS Version / Instance**: Kubernetes v1.20 on EKS 
- **Deployment**: Kubernetes
- **Severity**: Medium
- **Step where error happened**: Deploy

## Current Behavior
When using an external database with special characters in the password (_!?&) temporal fails to parse the connection string and the application does not start.

## Expected Behavior
Temporal should create the databases needed for airbyte to work

## Logs

```
setup postgresql schema
setup_postgres_schema
SCHEMA_DIR=/etc/temporal/schema/postgresql/v96/temporal/versioned
temporal-sql-tool --plugin postgres --ep my_host -u airbyte -p 5432 create --db temporal

failed: parse "postgres://airbyte:my_pass?!@my_host:5432/temporal_visibility?sslmode=disable": invalid port ":my_pass" after host.
```

</details>

## Steps to Reproduce
1. Setup an external database with special characters in the password
2. deploy airbyte 0.35.15-alpha on k8s using either helm chart or kustomize
3. temporal should fail

I fixed it by changing temporal image tag from 1.7.0 to 1.14.4 on my values.yaml.

## Are you willing to submit a PR?
Sure

**Comment by alafanechere** [comment]
Thank you @ordonezf for opening this issue and suggesting a fix!
This looks closely related to this one https://github.com/airbytehq/airbyte/issues/7067 
Let me know if you open a PR!
For your information, we also have a problem with temporal connecting with SSL to external database (https://github.com/airbytehq/airbyte/issues/9342)

**Comment by ordonezf** [comment]
@alafanechere I'll give it a try then! :)

> This looks closely related to this one https://github.com/airbytehq/airbyte/issues/7067

I don't think this one is an issue anymore, I deployed it myself with the config below, same as the one in the issue, and it works just fine.

```yaml
postgresql:
  enabled: false
externalDatabase:
  host: my-host
  user: my-user
  password: ""
  existingSecret: my-secret-name
  existingSecretPasswordKey: my-key
  database: airbyte
  port: 5432
```

**Comment by dylanbhughes** [comment]
I still experienced this bug with temporal image version 1.7.0. However, 1.14.4 did the trick. Thanks @ordonezf!

**Comment by evantahler** [comment]
Seems like this is solved!
