### ISSUE TITLE
Schema fetch returning empty on postgres >= 0.4.5

### ISSUE THREAD

**Issue by pcothenet** [airbytehq/airbyte#10548]
## Environment
- **Airbyte version**:  0.35.32-alpha
- **OS Version / Instance**: Amazon Linux 2
- **Deployment**: Docker
- **Source Connector and version**: Postgres 0.4.8
- **Destination Connector and version**: BigQuery 0.6.9
- **Severity**: High
- **Step where error happened**: Sync job / Update connector

## Current Behavior

- From the UI or API, the postgres schema being detected is empty (see API response below)
- The streams not being found, the data from the defined tables isn't being replicated. All syncs "succeed" but update 0 records (despite new records having been added in the source).

Reverting to postgres 0.4.4, solved the issue

## Expected Behavior

The connector should be able to detect the schema and perform replication.

## Logs

<details>
<summary>Here are the results returned by http://localhost:8000/api/v1/sources/discover_schema for 0.4.8</summary> 

```json
{
    "catalog": {
        "streams": []
    },
    "jobInfo": {
        "id": "535d03d4-e3f1-4dd3-aab4-8139eec0fa78",
        "configType": "discover_schema",
        "configId": "Optional[decd338e-5647-4c0b-adf4-da0e75f5a750]",
        "createdAt": 1645551876673,
        "endedAt": 1645551880367,
        "succeeded": true,
        "logs": {
            "logLines": ["2022-02-22 17:44:36 [32mINFO[m i.a.w.t.TemporalAttemptExecution(get):105 - Docker volume job log path: /tmp/workspace/e10b8060-b2d4-478e-89ef-c95072d59c5d/0/logs.log","2022-02-22 17:44:36 [32mINFO[m i.a.w.t.TemporalAttemptExecution(get):110 - Executing worker wrapper. Airbyte version: 0.35.32-alpha","2022-02-22 17:44:36 [32mINFO[m i.a.c.i.LineGobbler(voidCall):82 - Checking if airbyte/source-postgres:0.4.8 exists...","2022-02-22 17:44:36 [32mINFO[m i.a.c.i.LineGobbler(voidCall):82 - airbyte/source-postgres:0.4.8 was found locally.","2022-02-22 17:44:36 [32mINFO[m i.a.w.p.DockerProcessFactory(create):104 - Creating docker job ID: e10b8060-b2d4-478e-89ef-c95072d59c5d","2022-02-22 17:44:36 [32mINFO[m i.a.w.p.DockerProcessFactory(create):158 - Preparing command: docker run --rm --init -i -w /data/e10b8060-b2d4-478e-89ef-c95072d59c5d/0 --log-driver none --network host -v airbyte_workspace:/data -v /tmp/airbyte_local:/local airbyte/source-postgres:0.4.8 discover --config source_config.json","2022-02-22 17:44:37 [1;31mERROR[m i.a.c.i.LineGobbler(voidCall):82 - SLF4J: Class path contains multiple SLF4J bindings.","2022-02-22 17:44:37 [1;31mERROR[m i.a.c.i.LineGobbler(voidCall):82 - SLF4J: Found binding in [jar:file:/airbyte/lib/log4j-slf4j-impl-2.17.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]","2022-02-22 17:44:37 [1;31mERROR[m i.a.c.i.LineGobbler(voidCall):82 - SLF4J: Found binding in [jar:file:/airbyte/lib/slf4j-log4j12-1.7.30.jar!/org/slf4j/impl/StaticLoggerBinder.class]","2022-02-22 17:44:37 [1;31mERROR[m i.a.c.i.LineGobbler(voidCall):82 - SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.","2022-02-22 17:44:37 [1;31mERROR[m i.a.c.i.LineGobbler(voidCall):82 - SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]","2022-02-22 17:44:38 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 2022-02-22 17:44:38 [32mINFO[m i.a.i.s.p.PostgresSource(main):361 - starting source: class io.airbyte.integrations.source.postgres.PostgresSource","2022-02-22 17:44:38 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 2022-02-22 17:44:38 [32mINFO[m i.a.i.b.IntegrationCliParser(parseOptions):118 - integration args: {discover=null, config=source_config.json}","2022-02-22 17:44:38 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 2022-02-22 17:44:38 [32mINFO[m i.a.i.b.IntegrationRunner(run):88 - Sentry transaction event: 1b62360b0c7c47979b0df635de35fe42","2022-02-22 17:44:38 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 2022-02-22 17:44:38 [32mINFO[m i.a.i.b.IntegrationRunner(runInternal):106 - Running integration: io.airbyte.integrations.base.ssh.SshWrappedSource","2022-02-22 17:44:38 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 2022-02-22 17:44:38 [32mINFO[m i.a.i.b.IntegrationRunner(runInternal):107 - Command: DISCOVER","2022-02-22 17:44:38 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 2022-02-22 17:44:38 [32mINFO[m i.a.i.b.IntegrationRunner(runInternal):108 - Integration config: IntegrationConfig{command=DISCOVER, configPath='source_config.json', catalogPath='null', statePath='null'}","2022-02-22 17:44:38 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 2022-02-22 17:44:38 [33mWARN[m c.n.s.JsonMetaSchema(newValidator):338 - Unknown keyword order - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword","2022-02-22 17:44:38 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 2022-02-22 17:44:38 [33mWARN[m c.n.s.JsonMetaSchema(newValidator):338 - Unknown keyword examples - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword","2022-02-22 17:44:38 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 2022-02-22 17:44:38 [33mWARN[m c.n.s.JsonMetaSchema(newValidator):338 - Unknown keyword airbyte_secret - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword","2022-02-22 17:44:38 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 2022-02-22 17:44:38 [33mWARN[m c.n.s.JsonMetaSchema(newValidator):338 - Unknown keyword multiline - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword","2022-02-22 17:44:39 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 2022-02-22 17:44:39 [32mINFO[m i.a.i.b.s.SshTunnel(getInstance):170 - Starting connection with method: NO_TUNNEL","2022-02-22 17:44:40 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 2022-02-22 17:44:40 [32mINFO[m i.a.i.s.j.AbstractJdbcSource(discoverPrimaryKeys):209 - Discover primary keys for tables: []","2022-02-22 17:44:40 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 2022-02-22 17:44:40 [32mINFO[m i.a.i.s.p.PostgresSource(isCdc):253 - using CDC: false","2022-02-22 17:44:40 [32mINFO[m i.a.w.t.TemporalAttemptExecution(get):131 - Stopping cancellation check scheduling..."
            ]
        }
    }
}
```
</details>

## Steps to Reproduce
1.
2.
3.

## Are you willing to submit a PR?

Remove this with your answer.

**Comment by tghanken** [comment]
I'm also seeing this error on Postgres connector versions 0.4.5 through 0.4.8.  Downgrading to 0.4.4 resolved the issue for me.

**Comment by rparrapy** [comment]
I bumped into this issue when upgrading to 0.4.9. It only worked after downgrading to 0.4.4.

**Comment by pcothenet** [comment]
@alafanechere any update on this? This is either a pretty big bug or something strange with my setup.

**Comment by maofet** [comment]
Have the same issue!

**Comment by chstout** [comment]
I'm having the same issue.  For me it's the it's the fact that it's checking for my username as the grantee, but my user has a role that is the grantee.  Wouldn't we need to check for the complete nest of roles? 

https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/PostgresSource.java#L274-L312

**Comment by pcothenet** [comment]
@chstout this is a good clue. I'm also assigning permissions to a role, rather than directly to the user.

**Comment by chstout** [comment]
I think the top part of that query needs to be something akin to: 

```
SELECT nspname as schema_name,
       relname as table_name
FROM   pg_class 
JOIN   pg_namespace on pg_class.relnamespace = pg_namespace.oid
WHERE  has_table_privilege(?, pg_class.oid, 'SELECT')
```
? = username

additionally you could filter out info schema and pg_catalog if you want.

It can probably be combined with a single query without the UNION of those materialized views,  I just have no idea what's going on in that acl unpacking.  

Were the permission functions not being used for some reason?

**Comment by igormp** [comment]
Also facing the same issue, the offending PR seems to be [this one](https://github.com/airbytehq/airbyte/pull/10173/files), which was responsible for the version bump from 0.4.4 to 0.4.5.

I'm not that well versed into java, but I could try to debug this issue if someone could point where exactly I can look into that PR.

**Comment by seonixx** [comment]
Same problem here - no tables appear - had to revert back to 0.4.4.

**Comment by octavia-squidington-iii** [comment]
Marcos Marx commented: Just tried 0.4.9 which still has this issue for me.

**Comment by octavia-squidington-iii** [comment]
Marcos Marx commented: Have the same issue!

**Comment by octavia-squidington-iii** [comment]
Marcos Marx commented: Also facing the same issue, the offending PR seems to be [this one](https://github.com/airbytehq/airbyte/pull/10173/files), which was responsible for the version bump from 0.4.4 to 0.4.5.

I'm not that well versed into java, but I could try to debug this issue if someone could point where exactly I can look into that PR.

**Comment by igormp** [comment]
After doing a git bisect I managed to find the actual culprit for this issue: https://github.com/airbytehq/airbyte/commit/98b5aabd187a7338e01114c373a397d3aae3590e

Seems like a DB2 change ended up changing some stuff on the `AbstractJdbcSource`, which the pg connector didn't override for some reason.  I'll open a PR fixing this.

**Comment by SophieLohezic** [comment]
Hello. We have the same issue and have to use 0.4.4.
It looks like 0.4.4 fetches tables and materialized views. After that version, materialized views do not seem 'viewed'. I haven't found anything in the settings to specify we would like to fetch the views as well (it worked perfectly fine with 0.4.4 and below).
`2022-05-30 12:32:01 [44msource[0m > 2022-05-30 12:32:01 [32mINFO[m i.a.i.s.r.AbstractRelationalDbSource(queryTableFullRefresh):35 - Queueing query for table: company`
===> example of a table which works
`2022-05-30 12:32:01 [44msource[0m > 2022-05-30 12:32:01 [32mINFO[m i.a.i.s.r.AbstractDbSource(getSelectedIterators):186 - Skipping stream public.connections_per_patch because it is not in the source`
===> example of a table/view for which it does not work

**Comment by marcosmarxm** [comment]
@SophieLohezic did you try latest version of the connector?

**Comment by grishick** [comment]
This is most likely fixed now. @alexandr-shegeda I'll move this to your team to re-test and verify.

**Comment by SophieLohezic** [comment]
Hello @marcosmarxm. I test quite often when there is a new source-postgres available and I still have the same issue. The last I tried was  airbyte/source-postgres:0.4.28 on 0.35.61-alpha. I rollbacked again to airbyte/source-postgres:0.4.4

**Comment by SophieLohezic** [comment]
Out of the expected 228,362 records (7 streams), we have : 
- 228,362 records in 0.4.4 🙌
- - 0 records (0 out of of streams are read) in 0.4.10 💥
- 98, 547 records (only 5 out of streams are read) in 0.4.14 😥
- 98, 547 records (only 5 out of streams are read) in 0.4.28 😥

**Comment by DoNotPanicUA** [comment]
Hi @SophieLohezic ,
I've just released a version that should help you. Please try `0.4.30` and let me know if you still have an issue.

**Comment by SophieLohezic** [comment]
Thank you so much @DoNotPanicUA, it worked !!! 🎉🙏
