### ISSUE TITLE
Source Mailchimp: `email activity` stream missing data

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#14673]
This Github issue is synchronized with Zendesk:

**Ticket ID:** [#1553](https://airbyte7538.zendesk.com/agent/tickets/1553)
**Priority:** normal
**Group:** User Success Engineer
**Assignee:** Nataly Merezhuk

**Original ticket description:**

<blockquote><div class="zd-comment" dir="auto"><ul style="margin: 0 0 0 10px; padding: 0 0 0 20px;" dir="auto">
<li style="padding-bottom: 10px;">Is this your first time deploying Airbyte?: No</li>
<li style="padding-bottom: 10px;">OS Version / Instance: Ubuntu</li>
<li style="padding-bottom: 10px;">Memory / Disk: you can use something like 4Gb / 1 Tb</li>
<li style="padding-bottom: 10px;">Deployment: Kubernetes</li>
<li style="padding-bottom: 10px;">Airbyte Version: 0.39.25</li>
<li style="padding-bottom: 10px;">Source name/version:  Mailchimp</li>
<li style="padding-bottom: 10px;">Destination name/version: Json destination</li>
<li style="padding-bottom: 10px;">Step: Run the Mailchimp source with the Json destination with more than 700 email events</li>
<li style="padding-bottom: 10px;">Description:<br>
When I run the Mailchimp source to the JSON destination and compare it with what’s returned from the Mailchimp API’s, the output JSON is missing a lot of data. I spot-checked one campaign and found 61 events in the JSON output and the Mailchimp email_activity endpoint returns around 707.</li>
</ul> 

[<a href="https://discuss.airbyte.io/t/missing-mailchimp-email-activity-data/1830/1" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Nataly Merezhuk on 2022-07-12 at 22:36:*

<blockquote><div class="zd-comment" dir="auto">Hello, @murph! Could you please show me the Airbyte/server logs so I can see if you are getting an errors?<br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Nataly Merezhuk on 2022-07-13 at 13:56:*

<blockquote><div class="zd-comment" dir="auto">Thanks for digging into this - you are right, this is definitely not the intended behavior. I've opened an issue on Github, I or another team member will start work on this soon!<br></div></blockquote>

**Comment by murphpdx** [comment]
Hi, thanks for filing this issue for us. I just wanted to check in to see if we know when this issue will be prioritized?

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-07-19 at 20:23:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">Thank you for creating that issue! I just wanted to check in to see when the issue will be prioritized?</p> 

 [<a href="https://discuss.airbyte.io/t/missing-mailchimp-email-activity-data/1830/6" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Nataly Merezhuk on 2022-07-21 at 10:46:*

<blockquote><div class="zd-comment" dir="auto">@murph sorry for the wait, we have a few team members out this week. I asked one of my colleagues to set aside some time for this issue, so you'll be hearing something soon!<br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-08-25 at 05:13:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">Hi just checking in on this, has there been any movement?</p> 

 [<a href="https://discuss.airbyte.io/t/missing-mailchimp-email-activity-data/1830/8" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Nataly Merezhuk on 2022-09-01 at 21:14:*

<blockquote><div class="zd-comment" dir="auto">Hi, Amanda! Thank you for your patience. No movement on this yet but I have a few debugging ideas.<br><br>Could you possibly update Airbyte to the latest version and try the sync once more? I have tried to replicate the issue on my end, but from what I can see the connector is working correctly: all records emitted by Mailchimp are being committed to JSON.&nbsp;<br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-09-13 at 19:20:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">Did you use an incremental sync?</p> 

 [<a href="https://discuss.airbyte.io/t/missing-mailchimp-email-activity-data/1830/10" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-09-13 at 19:21:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">I’m not sure why you need to debug more. If you look at the linked code it shows that you’re treating it like the data is sorted but the API is not sorted. You’re also paginating in multiple ways at the same time.</p> 

 [<a href="https://discuss.airbyte.io/t/missing-mailchimp-email-activity-data/1830/11" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by davydov-d** [comment]
hey @marcosmarxm could you please verify with affected users if it is still the issue after upgrading the connector to the latest version?

**Comment by davydov-d** [comment]
The problem described in https://discuss.airbyte.io/t/missing-mailchimp-email-activity-data/1830 must have been fixed in https://github.com/airbytehq/airbyte/pull/20765

**Comment by murphpdx** [comment]
> The problem described in https://discuss.airbyte.io/t/missing-mailchimp-email-activity-data/1830 must have been fixed in #20765

I'm not sure why this was closed. It looks like you still have the bug. It seems like you're still setting the since field to the timestamp: https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-mailchimp/source_mailchimp/streams.py#L154

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2023-04-03 at 23:11:*

<blockquote><div class="zd-comment" dir="auto">Closed due to no response from requester.<br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2023-04-03 at 23:12:*

<blockquote><div class="zd-comment" dir="auto">Closed due to no response from requester.<br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2023-04-03 at 23:13:*

<blockquote><div class="zd-comment" dir="auto">Closed due to no response from requester.<br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2023-04-03 at 23:14:*

<blockquote><div class="zd-comment" dir="auto">Closed due to no response from requester.<br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2023-04-03 at 23:15:*

<blockquote><div class="zd-comment" dir="auto">Closed due to no response from requester.<br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2023-04-03 at 23:16:*

<blockquote><div class="zd-comment" dir="auto">Closed due to no response from requester.<br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2023-04-03 at 23:20:*

<blockquote><div class="zd-comment" dir="auto">Closed due to no response from requester.<br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2023-04-03 at 23:21:*

<blockquote><div class="zd-comment" dir="auto">Closed due to no response from requester.<br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2023-04-03 at 23:21:*

<blockquote><div class="zd-comment" dir="auto">Closed due to no response from requester.<br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2023-04-03 at 23:23:*

<blockquote><div class="zd-comment" dir="auto">Closed due to no response from requester.<br></div></blockquote>

**Comment by MattKravetz** [comment]
Hi all,

My team is also experiencing this issue, and it is causing us to ingest ~1/10th the data that we should be receiving from this endpoint.  This is occurring on `2.0.17` of the connector.    I believe the comment above re: sorting not being supported by the relevant endpoint is the underlying cause of this issue. Could this be reopened? Happy to assist with any testing/debugging of a fix if this would help!
