### ISSUE TITLE
🐛 Source MySQL: java.sql.SQLException: DAY_OF_MONTH

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#15161]
This Github issue is synchronized with Zendesk:

**Ticket ID:** [#1724](https://airbyte7538.zendesk.com/agent/tickets/1724)
**Priority:** normal
**Group:** Community Assistance Engineer
**Assignee:** Nataly Merezhuk

**Original ticket description:**

<blockquote><div class="zd-comment" dir="auto"><ul style="margin: 0 0 0 10px; padding: 0 0 0 20px;" dir="auto">
<li style="padding-bottom: 10px;">Is this your first time deploying Airbyte?: Yes</li>
<li style="padding-bottom: 10px;">Memory / Disk / CPU:  16Gb ram, 50gb, 8core / 16 logical processor</li>
<li style="padding-bottom: 10px;">Deployment: Docker Desktop</li>
<li style="padding-bottom: 10px;">Airbyte Version: 0.39.37-alpha</li>
<li style="padding-bottom: 10px;">Source name/version: MySQL 0.5.6</li>
<li style="padding-bottom: 10px;">Destination name/version: Postgres 14</li>
<li style="padding-bottom: 10px;">Step: Issue is happening on sync</li>
<li style="padding-bottom: 10px;">Description:  I have two connectors with mysql and both keep failing either with sql exception of MONTH or YEAR for the either.</li>
</ul>
<p dir="auto"><a href="https://discuss.airbyte.io/uploads/short-url/luWBq6tUKMuizdUNIPRBIohL7jt.txt" style="color: #006699; font-weight: bold; text-decoration: none;" rel="noreferrer">logs-13.txt</a> (1.0 MB)</p> 

[<a href="https://discuss.airbyte.io/t/msql-source-sql-exception-month-year/2016/1" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-07-27 at 08:41:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">I did additional tests by creating a view from the original table without date related fields (strings) and sync was successful, there seems to be an issue with one of the date columns regarding to the data maybe.</p>
<p dir="auto">Not sure how and what to find.</p> 

 [<a href="https://discuss.airbyte.io/t/msql-source-sql-exception-month-year/2016/2" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Nataly Merezhuk on 2022-07-27 at 13:19:*

<blockquote><div class="zd-comment" dir="auto">Hello and welcome to the Airbyte community, @antonapua! It looks like you may be passing the wrong format in date related fields. Could you try using an instance of <code>LocalDate</code> instead of a string?<br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-07-28 at 04:20:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">Hi <a href="/u/natalyjazzviolin" style="color: #006699; font-weight: bold; text-decoration: none;" rel="noreferrer">@natalyjazzviolin</a>,</p>
<p dir="auto">I am not sure what LocalDate you’re referring to, is that Java? I don’t have access to change the existing mysql table not control over what data goes into it.</p>
<p dir="auto">I did create a mysql view table and tried to apply CAST as DATETIME() however, I still encountered the same issue.</p> 

 [<a href="https://discuss.airbyte.io/t/msql-source-sql-exception-month-year/2016/4" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-07-28 at 07:38:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">Issue seems to be related to <a href="https://github.com/airbytehq/airbyte/issues/3931" rel="noopener nofollow ugc noreferrer" style="color: #006699; font-weight: bold; text-decoration: none;">Source MySQL: Connector fails if source contains "tricky" date values · Issue #3931 · airbytehq/airbyte · GitHub</a> however I thought it’s fixed already.</p> 

 [<a href="https://discuss.airbyte.io/t/msql-source-sql-exception-month-year/2016/5" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-07-28 at 08:33:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">applied zerodatetimebehavior=Converttonull still having the same issue<br>
<a href="https://discuss.airbyte.io/uploads/short-url/gzi9ttrI8kqMnn885GvS1JjOi5v.txt" style="color: #006699; font-weight: bold; text-decoration: none;" rel="noreferrer">logs-99.txt</a> (2.6 MB)</p> 

 [<a href="https://discuss.airbyte.io/t/msql-source-sql-exception-month-year/2016/6" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Nataly Merezhuk on 2022-08-01 at 15:29:*

<blockquote><div class="zd-comment" dir="auto">From the latest logs it looks like the problem is now in DAY_OF_MONTH. I found another related issue that's been resolved:<br><a rel="noopener noreferrer" href="https://github.com/airbytehq/airbyte/issues/5070">https://github.com/airbytehq/airbyte/issues/5070</a><br><br>I think the best course of action is to escalate this to GitHub, so I'lll do that next!<br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Nataly Merezhuk on 2022-08-01 at 15:32:*

<blockquote><div class="zd-comment" dir="auto">Please feel free to add any details here:<br><a rel="noopener noreferrer" href="https://github.com/airbytehq/airbyte/issues/15161">https://github.com/airbytehq/airbyte/issues/15161</a><br></div></blockquote>

**Comment by antonapua** [comment]
Identified issue where date value had 00 as day. wish this was ignored or converted to null.

**Comment by grishick** [comment]
@marcosmarxm this was likely fixed fairly recently. Can we ask the user to retry?

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Nataly Merezhuk on 2022-08-30 at 18:53:*

<blockquote><div class="zd-comment" dir="auto">Hello again, @antonapua. Could you retry - looks like the issue might have been fixed!<br></div></blockquote>

**Comment by akashkulk** [comment]
Closing this out for now, since no issues were reported by the user after the fix

**Comment by octav-s** [comment]
Still getting the issue in August 2023. I believe it is related to some dates being null. I've triead any and all parameters for the JDBC connector, it made no difference. I've checked the worker log and besides the DAY_OF_MONTH error, it is also showing another error, "c.n.s.DateTimeValidator(tryParse):82 - Invalid date-time: No zone offset information found". I've chacked all date and datetime fields, the values are either valid dates or NULL values.
[worker_log.txt](https://github.com/airbytehq/airbyte/files/12289680/worker_log.txt)
[f7199418_cea5_41e1_a66c_3e72df231d5f_job_8_attempt_3.txt](https://github.com/airbytehq/airbyte/files/12289719/f7199418_cea5_41e1_a66c_3e72df231d5f_job_8_attempt_3.txt)
[f7199418_cea5_41e1_a66c_3e72df231d5f_job_8_attempt_2.txt](https://github.com/airbytehq/airbyte/files/12289721/f7199418_cea5_41e1_a66c_3e72df231d5f_job_8_attempt_2.txt)
[f7199418_cea5_41e1_a66c_3e72df231d5f_job_8_attempt_1.txt](https://github.com/airbytehq/airbyte/files/12289723/f7199418_cea5_41e1_a66c_3e72df231d5f_job_8_attempt_1.txt)

**Comment by octav-s** [comment]
PS: I've been getting the same error, DAY_OF_MONTH, in AWS Glue as well. I have not been able to figure out why it happens.
