### ISSUE TITLE
🐛 Source MySQL: `java.lang.IllegalArgumentException` check connection after update from 0.6.8 to 0.6.9+

### ISSUE THREAD

**Issue by hellmund** [airbytehq/airbyte#16860]
## Environment
- **Airbyte version**: 0.40.7 and 0.40.6 (upgraded from 0.40.4)
- **OS Version / Instance**: Amazon Linux 2 AMI, EC2 t3a.large
- **Deployment**: Docker
- **Source Connector and version**: MySQL 0.6.13 and 0.6.11 (upgraded from 0.6.8)
- **Destination Connector and version**: N/A
- **Step where error happened**: Sync job and also when testing existing connection

## Current Behavior
After upgrading Airbyte and the corresponding MySQL source connector, the connector is unable to establish a connection, failing during config verification. This breaks all previously setup connections with this source connector.
Also, editing the source and trying to hit "Save changes and test" now only shows an "Internal error"
Note: Using SSL preferred, STANDARD replication method, No Tunnel 
Creating a brand new source connection from scratch works, but this discards all data in the existing _scd tables.

## Expected Behavior
Migrate existing configs to new connector requirements or include ability to read previous config formats.
No "Internal error" when trying to edit the configuration.

## Logs
[logs-1766.txt](https://github.com/airbytehq/airbyte/files/9597454/logs-1766.txt)

## Steps to Reproduce
1. Have functioning connection with MySQL source 0.6.8
2. Upgrade MySQL source connector to 0.6.11 or newer

## Are you willing to submit a PR?
No

**Comment by marcosmarxm** [comment]
This error is related to variable in the airbyte-internal database.

Error:
```
2022-09-19 08:25:39 [1;31mERROR[m i.a.s.p.JobNotifier(notifyJob):133 - Unable to read configuration:
java.lang.NullPointerException: null value in entry: max_seconds_before_source_state_message_emitted=null
	at com.google.common.collect.CollectPreconditions.checkEntryNotNull(CollectPreconditions.java:33) ~[guava-31.1-jre.jar:?]
	at com.google.common.collect.ImmutableMapEntry.<init>(ImmutableMapEntry.java:54) ~[guava-31.1-jre.jar:?]
	at com.google.common.collect.ImmutableMap.entryOf(ImmutableMap.java:339) ~[guava-31.1-jre.jar:?]
	at com.google.common.collect.ImmutableMap$Builder.put(ImmutableMap.java:449) ~[guava-31.1-jre.jar:?]
	at io.airbyte.scheduler.persistence.job_tracker.TrackingMetadata.generateJobAttemptMetadata(TrackingMetadata.java:118) ~[io.airbyte.airbyte-scheduler-scheduler-persistence-0.40.7.jar:?]
	at io.airbyte.scheduler.persistence.JobNotifier.notifyJob(JobNotifier.java:82) ~[io.airbyte.airbyte-scheduler-scheduler-persistence-0.40.7.jar:?]
	at io.airbyte.scheduler.persistence.JobNotifier.notifyJob(JobNotifier.java:61) ~[io.airbyte.airbyte-scheduler-scheduler-persistence-0.40.7.jar:?]
	at io.airbyte.scheduler.persistence.JobNotifier.failJob(JobNotifier.java:167) ~[io.airbyte.airbyte-scheduler-scheduler-persistence-0.40.7.jar:?]
	at io.airbyte.workers.temporal.scheduling.activities.JobCreationAndStatusUpdateActivityImpl.jobFailure(JobCreationAndStatusUpdateActivityImpl.java:229) ~[io.airbyte-airbyte-workers-0.40.7.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
	at io.temporal.internal.activity.POJOActivityTaskHandler$POJOActivityInboundCallsInterceptor.execute(POJOActivityTaskHandler.java:214) ~[temporal-sdk-1.8.1.jar:?]
	at io.temporal.internal.activity.POJOActivityTaskHandler$POJOActivityImplementation.execute(POJOActivityTaskHandler.java:180) ~[temporal-sdk-1.8.1.jar:?]
	at io.temporal.internal.activity.POJOActivityTaskHandler.handle(POJOActivityTaskHandler.java:120) ~[temporal-sdk-1.8.1.jar:?]
	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:204) ~[temporal-sdk-1.8.1.jar:?]
	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:164) ~[temporal-sdk-1.8.1.jar:?]
	at io.temporal.internal.worker.PollTaskExecutor.lambda$process$0(PollTaskExecutor.java:93) ~[temporal-sdk-1.8.1.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(T
```

@alovew could you help here?

**Comment by alovew** [comment]
@marcosmarxm and @hellmund, this bug is fixed in OSS and was released 2 days ago in 0.40.8 release. There's another new release after this one so I would recommend upgrading to 0.40.9.

**Comment by hellmund** [comment]
@alovew I've just upgraded to 0.40.9 and the issue is still present, e.g. when re-testing a connection:

`Verification error(s) occurred for CHECK. Errors: [$.replication_method: should be valid to one and only one of the schemas , $.replication_method: string found, object expected]`

**Comment by marcosmarxm** [comment]
@hellmund can you share the complete log? The validation you're posting if a warning

**Comment by hellmund** [comment]
@marcosmarxm yes, here is a log from just now:
[b03b3214_2dab_4949_b52e_5d5887257125_logs_2120_txt.txt](https://github.com/airbytehq/airbyte/files/9648403/b03b3214_2dab_4949_b52e_5d5887257125_logs_2120_txt.txt)

**Comment by marcosmarxm** [comment]
The last log you shared doesn't have the same error message. @hellmund did you sync finished, failed with an error or only get stuck?

**Comment by marcosmarxm** [comment]
I was able to reproduce @hellmund problem.
I successfully created one MySQL connector using 0.6.8.
After I updated the connector to version 0.6.13 and the connector CHECK operation started failed.
Airbyte only returns: `Internal Server Error: null`
![image](https://user-images.githubusercontent.com/5154322/192378354-b5d0d2bc-817f-4c11-8d96-23056ac5947b.png)

Capturing the API response in Network tab:
payload
```json
{"connectionConfiguration":{"ssl":true,"host":"*****","port":3306,"database":"sourcetest","password":"**********","ssl_mode":{"mode":"preferred"},"username":"airbyte","tunnel_method":{"tunnel_host":"*****","tunnel_port":22,"tunnel_user":"airbyte","tunnel_method":"SSH_PASSWORD_AUTH","tunnel_user_password":"**********"},"replication_method":{"method":"STANDARD"}},"name":"MySQL","sourceId":"76d50174-6780-4ff5-9582-541f0dc1eef4"}
```
response:
```json
{
    "message": "Internal Server Error: null",
    "exceptionClassName": "java.lang.IllegalArgumentException",
    "exceptionStack": [
        "java.lang.IllegalArgumentException",
        "\tat com.google.common.base.Preconditions.checkArgument(Preconditions.java:131)",
        "\tat io.airbyte.config.persistence.split_secrets.JsonSecretsProcessor.copySecrets(JsonSecretsProcessor.java:117)",
        "\tat io.airbyte.config.persistence.split_secrets.JsonSecretsProcessor.copySecrets(JsonSecretsProcessor.java:152)",
        "\tat io.airbyte.server.converters.ConfigurationUpdate.source(ConfigurationUpdate.java:52)",
        "\tat io.airbyte.server.handlers.SchedulerHandler.checkSourceConnectionFromSourceIdForUpdate(SchedulerHandler.java:158)",
        "\tat io.airbyte.server.apis.ConfigurationApi.lambda$checkConnectionToSourceForUpdate$35(ConfigurationApi.java:490)",
        "\tat io.airbyte.server.apis.ConfigurationApi.execute(ConfigurationApi.java:856)",
        "\tat io.airbyte.server.apis.ConfigurationApi.checkConnectionToSourceForUpdate(ConfigurationApi.java:490)",
        "\tat java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)",
        "\tat java.base/java.lang.reflect.Method.invoke(Method.java:578)",
        "\tat org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)",
        "\tat org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124)",
        "\tat org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167)",
        "\tat org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:219)",
        "\tat org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79)",
        "\tat org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:469)",
        "\tat org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:391)",
        "\tat org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:80)",
        "\tat org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:253)",
        "\tat org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)",
        "\tat org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)",
        "\tat org.glassfish.jersey.internal.Errors.process(Errors.java:292)",
        "\tat org.glassfish.jersey.internal.Errors.process(Errors.java:274)",
        "\tat org.glassfish.jersey.internal.Errors.process(Errors.java:244)",
        "\tat org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)",
        "\tat org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:232)",
        "\tat org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680)",
        "\tat org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394)",
        "\tat org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)",
        "\tat org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:366)",
        "\tat org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:319)",
        "\tat org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)",
        "\tat org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:763)",
        "\tat org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:569)",
        "\tat org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)",
        "\tat org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1377)",
        "\tat org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)",
        "\tat org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:507)",
        "\tat org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)",
        "\tat org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1292)",
        "\tat org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)",
        "\tat org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)",
        "\tat org.eclipse.jetty.server.Server.handle(Server.java:501)",
        "\tat org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)",
        "\tat org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:556)",
        "\tat org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)",
        "\tat org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)",
        "\tat org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)",
        "\tat org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)",
        "\tat org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)",
        "\tat org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)",
        "\tat org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)",
        "\tat org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)",
        "\tat org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)",
        "\tat org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375)",
        "\tat org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)",
        "\tat org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)",
        "\tat java.base/java.lang.Thread.run(Thread.java:1589)"
    ]
}
```

The first version after 0.6.8 introduces the issue is 0.6.9: https://github.com/airbytehq/airbyte/pull/16216/files#diff-b80504e3c36c712838812ede7c87b0399b30d1f87aee6cb01a94655bc03a04d1

**Comment by marcosmarxm** [comment]
I was able to workaround the issue by editing the `actor` table.
```sql
update actor set configuration = jsonb_set(configuration, '{replication_method}', '{"method":"STANDARD"}') where id = '76d50174-6780-4ff5-9582-541f0dc1eef4';
```

where `76d50174-6780-4ff5-9582-541f0dc1eef4` is my source id.
![image](https://user-images.githubusercontent.com/5154322/192391400-8b49d3b3-27f6-40fe-9666-f38b38395748.png)

**Comment by czomo** [comment]
FYI For problems with Microsoft SQL connector follow steps from https://docs.airbyte.com/integrations/sources/mssql/#upgrading-from-0417-and-older-versions-to-0418-and-newer-versions

**Comment by octavia-squidington-iii** [comment]
At Airbyte, we seek to be clear about the project priorities and roadmap.  This issue has not had any activity for 180 days, suggesting that it's not as critical as others.  It's possible it has already been fixed. It is being marked as stale and will be closed in 20 days if there is no activity. To keep it open, please comment to let us know why it is important to you and if it is still reproducible on recent versions of Airbyte.

**Comment by marcosmarxm** [comment]
Latest version of MySQL connector now is 3.6.17 I'm closing this because it reports a problem with a very old version of the connector. Please try with latest version.
