### ISSUE TITLE
nginx: [emerg] host not found in upstream "$CONNECTOR_BUILDER_API_HOST"

### ISSUE THREAD

**Issue by tfoldi** [airbytehq/airbyte#19642]
## Environment
- **Airbyte version**: Chart airbyte-0.41.0
- **OS Version / Instance**: Kubernetes
- **Deployment**: Helm
- **Step where error happened**: Helm install

## Current Behavior

Worker does not start after helm install

```
❯ k get pods -n airbyte
NAME                                               READY   STATUS             RESTARTS   AGE
airbyte-airbyte-bootloader                         0/1     Completed          0          9m58s
airbyte-cron-74ffdd6c46-twhrm                      1/1     Running            0          9m32s
airbyte-db-0                                       1/1     Running            1          10m
airbyte-minio-0                                    1/1     Running            0          9m59s
airbyte-pod-sweeper-pod-sweeper-557f5dc657-27d4t   1/1     Running            0          9m31s
airbyte-server-767949f48-72xcs                     1/1     Running            0          9m32s
airbyte-temporal-5f47b89b68-vrn6j                  1/1     Running            0          9m31s
airbyte-webapp-d64c5757f-qcvhj                     0/1     CrashLoopBackOff   6          9m32s
airbyte-worker-7c74b896fb-2ddqc                    1/1     Running            0          9m31s
```

## Expected Behavior

Helm install should work by default

## Logs

```
❯ k logs airbyte-webapp-d64c5757f-qcvhj  -n airbyte
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
20-envsubst-on-templates.sh: Running envsubst on /etc/nginx/templates/default.conf.template to /etc/nginx/conf.d/default.conf
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
2022/11/21 07:33:27 [emerg] 1#1: host not found in upstream "$CONNECTOR_BUILDER_API_HOST" in /etc/nginx/conf.d/default.conf:6
nginx: [emerg] host not found in upstream "$CONNECTOR_BUILDER_API_HOST" in /etc/nginx/conf.d/default.conf:6

```

## Steps to Reproduce
1. wget https://raw.githubusercontent.com/airbytehq/airbyte/master/charts/airbyte/values.yaml
2. helm install -n airbyte --values values.yaml airbyte airbyte/airbyte

**Comment by lmossman** [comment]
Thanks for opening this issue, we are actively working on a fix for this. I will update here when we have more details.

**Comment by lmossman** [comment]
We have merged in the [fix](https://github.com/airbytehq/airbyte/pull/19554) for this issue, and I am now working on releasing a new version of Airbyte so that users can pull in the fix. Will update here when that is out

**Comment by lmossman** [comment]
@tfoldi the fix has been released in master. Please upgrade to airbyte v0.40.22 and try again, and feel free to reopen this issue if you run into any more problems. Thanks!

**Comment by zeGzD** [comment]
The issue is still present on v0.40.22 (encountered when migrating from v0.40.18).

**Comment by ASchmidtGit** [comment]
I can confirm this issue still exists when deploying over docker compose in a swarm

**Comment by ASchmidtGit** [comment]
@zeGzD Deleting the container-name properties and renaming server to airbyte-server fixed the issue for me and everything runs
