### ISSUE TITLE
Source Google Ads: Normalization produces improper data since introduction of "segments.hour" in 0.2.3

### ISSUE THREAD

**Issue by tigitz** [airbytehq/airbyte#20283]
## Environment
- **Airbyte version**:  0.40.14
- **OS Version / Instance**: airbyte docker-compose
- **Deployment**: docker-compose in local
- **Source Connector and version**: Google Ads 0.2.5 
- **Destination Connector and version**: Postgres 0.3.26
- **Step where error happened**: Dbt Normalization

## Current Behavior
While normalizing google ads extracted data with the `Incremental | Deduped + history` strategy,  since the introduction of the `segments.hour` in `0.2.3` I believe, the row normalized in the final table `campaign` is now a single hour data of the day.

Meaning 
```sql
SELECT _airbyte_data ->> 'segments.date' as segment_date
     , (_airbyte_data ->> 'segments.hour')::float as segment_hour
     , (_airbyte_data ->> 'metrics.impressions')::float as impressions
FROM public._airbyte_raw_campaigns
WHERE _airbyte_data ->> 'campaign.id' = '9605993431' AND _airbyte_data ->> 'segments.date' = '2022-11-30'
```
Gives
![image](https://user-images.githubusercontent.com/1524501/206650918-49a9e1f0-7e40-468f-88cb-157d1028412c.png)

But
```sql
SELECT "segments.date",
       "segments.hour",
       "metrics.impressions"
FROM public.campaigns
WHERE "campaign.id"= '9605993431' AND "segments.date" = '2022-11-30';
```

Gives 
![image](https://user-images.githubusercontent.com/1524501/206651110-4007b2e0-8505-4b6c-9706-544412d2c8ba.png)

## Expected Behavior
I would expect it to keep the previous behavior by aggregating data by the date, meaning having this result basically in `campaigns`
```sql
SELECT _airbyte_data ->> 'segments.date' as segment_date
     , SUM((_airbyte_data ->> 'metrics.impressions')::float) as impressions
FROM public._airbyte_raw_campaigns
WHERE _airbyte_data ->> 'campaign.id' = '9605993431' AND _airbyte_data ->> 'segments.date' = '2022-11-30'
GROUP BY _airbyte_data ->> 'segments.date'
```

But I understand since the introduction of `segments.hour` it adds more granularity to the data so aggregating here would mean losing this new granularity, defeating the purpose of introducing it.

In this case I would expect the final `campaigns` table to properly show all the the rows for each hours.

## Hints

I believe problem is in the generated `campaign_scd.sql` where it defines uniqueness by partitioning by `segments.date` only, missing the new `segments.hour` granularity introduced.

```sql
 -- line 101
    case when row_number() over (
        partition by "campaign.id", "segments.date"
        order by
            "segments.date" is null asc,
            "segments.date" desc,
            _airbyte_emitted_at desc
      ) = 1 then 1 else 0 end as _airbyte_active_row,
```

**Comment by baudouin-notilus** [comment]
Having the exact same issue here!

A quick fix I did is working with `campaigns_scd` table instead of `campaigns` table, but it is a bit of a hack.

**Comment by tigitz** [comment]
Yeah that's unfortunate, issue seems quite problematic since it results in incorrect data and forces to downgrade AFAIU. 

I'm wondering how users using the GADS source haven't hit this issue or realised they're affected. Seems quite a priority for airbyte maintainers to fix it. Tried to help as much as I can with clear explanations and solutions hints but despite that there doesn't seem to be any traction :man_shrugging:

**Comment by hanslemm** [comment]
Hi!

Yesterday, this issue was fixed with PR #23999.

Update your connector **and refresh the source schema** to update the incremental sync.

**Comment by baudouin-notilus** [comment]
Hi!

Thanks a lot for working on this, I will do the updates soon!
Have a great day,

Baudouin

**Comment by hanslemm** [comment]
This issue was fixed in yesterday's PR for Source Google Ads #23999.

Update the connector & refresh source schema to make use of the fixed incremental sync.

**Comment by tigitz** [comment]
@hanslemm @evantahler tried it but didn't fix anything.

`campaigns` model
![image](https://user-images.githubusercontent.com/1524501/225290886-675027ef-062b-41d6-890f-e2a9bc47ff49.png)

`campaigns_scd` model
![image](https://user-images.githubusercontent.com/1524501/225291136-fbbf50a1-6f74-410c-b358-bc17251a4965.png)

**Comment by hanslemm** [comment]
It is important to refresh the source schema after updating the connector, otherwise the SCD logic is still the old one. Could you confirm that this step was done?

**Comment by tigitz** [comment]
Yes I did it
![image](https://user-images.githubusercontent.com/1524501/225302078-1d9822b8-444a-4ca9-ba69-ec3d9132122c.png)

**Comment by tigitz** [comment]
@hanslemm Could you copy / paste here your generated dbt scd model please ? I don't see any change since your connector update and I'm convinced this is the file that needs the [changes mentioned above](https://github.com/airbytehq/airbyte/issues/20283#issuecomment-1466915920)

AFAIU airbyte generates a dbt project for each sync so there's no chance that the fact it didn't change could be related to a leftover of previous syncs when the connector was not in the latest version, right ?

**Comment by hanslemm** [comment]
Could you confirm me that the primary key of your replication setting is as follows for the `campaigns`:
![image](https://user-images.githubusercontent.com/32077629/225303533-12c35c8f-5aee-45bc-910e-ce71280ac3c5.png)

**Comment by tigitz** [comment]
@hanslemm huh :man_facepalming: I misread and confused refreshing the schema and resetting the data

Now it makes sense and the generated scd model contains the appropriate changes.

Thanks, I wish there would be a notification or automatic process that says "Hey this connector upgrade requires a schema refresh, do it (or we did it automatically for you)"

**Comment by evantahler** [comment]
Glad you solved, and thanks for the assist @hanslemm! 

Tagging @andyjih, who is looking into schema updates and notifying people about them
