### ISSUE TITLE
UI doesn't allow selecting individual fields within a stream

### ISSUE THREAD

**Issue by varunbpatil** [airbytehq/airbyte#2208]
## Expected Behavior
As shown in this postgres → postgres [tutorial video](https://www.youtube.com/watch?v=Rcpt5SVsMpk), I was expecting to be able to select individual fields within the stream to sync.

Also, for incremental sync, I was expecting to be able to select a particular field in the `users` table to act as the cursor field.

## Current Behavior
The UI doesn't allow selecting individual fields within the stream (no checkboxes for `public.users.id` and `public.users.col1` in the image below).

Also, the dropdown for the incremental sync doesn't show the correct cursor field options - it shows the table name (`public.users`) instead of the fields within the table (`public.users.id` or `public.users.col1`).

![image](https://user-images.githubusercontent.com/1353218/109109200-e18fed00-775a-11eb-9b2d-61a8f9141cc8.png)

## Steps to Reproduce
1. Create Postgres source.
2. Create Postgres destination.
3. Try to set up a connection. 

## Severity of the bug for you
Medium

## Airbyte Version
0.14.4-alpha

## Connector Version (if applicable)
Postgres 0.1.13

## Additional context
*Environment, version, integration...*

**Comment by ChristopheDuong** [comment]
This sounds like it might have been fixed recently: https://github.com/airbytehq/airbyte/pull/2131

Could you try again with the latest versions, please?

Airbyte Version 0.15.0-alpha
Connector Version Postgres 0.1.16

Thanks!

**Comment by varunbpatil** [comment]
Thank you. The cursor selection seems to be fixed, but I still don't see checkboxes to select individual fields within the stream to sync.

![image](https://user-images.githubusercontent.com/1353218/109259732-d7d1bc80-7822-11eb-909d-5333b8ea69bd.png)

**Comment by cgardens** [comment]
Yeah. We don't support field level section right now. Here is an issue to track that: https://github.com/airbytehq/airbyte/issues/2227. This is something we definitely do plan to support.

Can you mention the urgency of this for you right now? Could you share your use case for what you're trying to filter and why? This will help us set the prioritiy.

**Comment by varunbpatil** [comment]
Thanks, @cgardens. My use-case is for filtering industrial sensor data (as detailed in #2224). Not a very high priority at the moment compared to #2224 itself.
