### ISSUE TITLE
[Low-Code Custom Component] NestedStateCartesianProductStreamSlicer

### ISSUE THREAD

**Issue by grubberr** [airbytehq/airbyte#22873]
## Introduction to the Problem

The low-code framework component, [CartesianProductStreamSlicer](https://github.com/airbytehq/airbyte/blob/master/airbyte-cdk/python/airbyte_cdk/sources/declarative/stream_slicers/cartesian_product_stream_slicer.py#L17), allows for the attachment of multiple slicers to generate the cartesian product of all items.

As an example:

```
   item1 2022-01-01T01:00:00Z
   item1 2022-02-01T01:00:00Z
   item2 2022-01-01T01:00:00Z
   item2 2022-02-01T01:00:00Z
```

There are currently three low-code connectors that use an extended version of this component:

```python
class NestedStateCartesianProductStreamSlicer(CartesianProductStreamSlicer):
    ...
```

- source-posthog, [EventsCartesianProductStreamSlicer](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-posthog/source_posthog/components.py#L54)
- source-railz, [NestedStateCartesianProductStreamSlicer](https://github.com/airbytehq/airbyte/blob/c45d6072c15bc798997f79b65ff5953f34caed91/airbyte-integrations/connectors/source-railz/source_railz/components.py#L89)
- source-twilio, [NestedStateCartesianProductStreamSlicer](https://github.com/airbytehq/airbyte/blob/080a246574d744af1b8aeb85a7002186738809b6/airbyte-integrations/connectors/source-twilio/source_twilio/components.py#L14)

 The extended version of this component, `NestedStateCartesianProductStreamSlicer` re-implements `update_cursor` method which allows storing nested state:

```json
{
  "item1": {
    "updated_at": "2022-02-01T01:00:00Z"
  },
  "item2": {
    "updated_at": "2022-02-01T01:00:00Z"
  }
}
```

## Potential for Migration to Low Code Framework

`NestedStateCartesianProductStreamSlicer` can be a potential candidate for migration to the low-code framework.

**Comment by girarda** [comment]
should be fixed with the partition routers and the datetimebasedcursor

**Comment by zh4ngx** [comment]
I still have an issue with source-railz #42416 
I think it has to do with a type mismatch in the extended version

**Comment by zh4ngx** [comment]
Would definitely be helpful to migrate this to low code - API change has caused 2 of these implementations to break

**Comment by zh4ngx** [comment]
> should be fixed with the partition routers and the datetimebasedcursor

can you explain how to use these together?
