### ISSUE TITLE
Source Hubspot: Database Error in model contacts_properties

### ISSUE THREAD

**Issue by dis-sid** [airbytehq/airbyte#23864]
## Environment
- **Airbyte version**:  example is 0.40.18
- **OS Version / Instance**: GCP E2 highmem
- **Deployment**: Kubernetes (GKE)
- **Source Connector and version**: Hubspot 0.3.2 
- **Destination Connector and version**: BigQuery 1.2.14 
- **Step where error happened**: Sync Job

## Current Behavior
*Tell us what happens.*
A few days ago our hubspot -> bigquery connection started to fail when syncing Hubspot Contacts properties at the normalization step.

The relevant part of the log looks like :

`Database Error in model contacts_properties (models/generated/airbyte_tables/hubspot/contacts_properties.sql)
Invalid date: '2022-03-25T11:08:03.459000+00:00'`

Searching for these invalid dates in contact properties I've been able to link the error to the `hs_latest_source_timestamp` field.

We also see earlier in the logs `DateTimeValidator` errors.

## Expected Behavior
*Tell us what should happen.*
The sync should successfully complete.
## Logs

[sync_logs.txt](https://github.com/airbytehq/airbyte/files/10919629/sync_logs.txt)
## Steps to Reproduce
1. Setup a BigQuery Destination
2. Setup a Hubspot source
3. Setup an Hubspot to BigQuery connection with the Contacts stream
4. Start a Sync

## Are you willing to submit a PR?

Remove this with your answer.

**Comment by pvanacker** [comment]
Thanks for reporting ths issue. I have the same error since yesterday - did you find any workaround, until a proper fix is released ?

**Comment by dis-sid** [comment]
> Thanks for reporting this issue. I have the same error since yesterday - did you find any workaround, until a proper fix is released ?

I don't know Airbyte enough to find what's going on, mess with its generated tables schema or patch/deploy a custom version of it without spending too much times. So I disabled the contacts stream and made a quick script using https://github.com/HubSpot/hubspot-api-python to get important contact data in a new table and referenced it in the table view I expose to analysts.

**Comment by bnchrch** [comment]
Hey all, Ben here from Airbyte.

Ok so were thinking that this issue is likely resolved based on a fix we deployed last week.

However existing Hubspot connection uses will have to refresh their schema.

You can do this by
1. Navigating to the connection using hubspot in your workspace
2. Going to the "replication" tab
3. Clicking "refresh schema" in the bottom right

![image](https://user-images.githubusercontent.com/1325608/225439343-05326372-2228-4814-87ca-7365f668deca.png)

Here's a [tutorial](https://docs.airbyte.com/cloud/managing-airbyte-cloud/manage-schema-changes/) from our cloud docs that lays out similar steps from refreshing your schema in case this helps.

Please let me know if this solves your issue! Would love to get you all unblocked

**Comment by pvanacker** [comment]
Thanks @bnchrch it works if the schema is refreshed :+1:

**Comment by ancq99** [comment]
Hi, recently I've encountered same error, but unfortunately @bnchrch solution did not fix it for me. 

# Environment
- Airbyte version: 0.30.34-alpha
- OS Version / Instance: Ubuntu 22.04.1 LTS
- Deployment: Local Machine 
- Source Connector and version: Hubspot 0.3.2
- Destination Connector and version: BigQuery 1.2.16
- Step where error happened: Sync Job

# Current Behavior
It is nearly identical as op's (dis-sid's) except I am not sure whether the invalid timestamp is connected with hs_latest_source_timestamp. The invalid timestamp is different with each sync attempt. 

# Logs 
[logs-14468-0.txt](https://github.com/airbytehq/airbyte/files/11000621/logs-14468-0.txt)


Do you have any more solutions how to solve it?

**Comment by dis-sid** [comment]
Works for me too after schema update, thanks @bnchrch !
