### ISSUE TITLE
GitHub resync causes older database rows to be removed

### ISSUE THREAD

**Issue by yeedster** [airbytehq/airbyte#2607]
## Expected Behavior
After a sync I expect only new row data to be added to the database.  

## Current Behavior
Old rows are removed and only new data is present in the tables

## Logs
log attached from last sync.

## Steps to Reproduce
1. Connect AirBytes to a GitHub repo with existing pull_request / commits / comments/ users
1. Sync AirBytes to get initial table and data
1.  Re-Sync AirBytes to the same repo

## Severity of the bug for you
Medium - WorkAround is currently to wipe the whole table and do another sync.

## Airbyte Version
.17-alpha

## Connector Version (if applicable)
Found in the admin page in the UI in the respective Source or Destination tab.

## Additional context
GitHub, PostGres, AirBytes
[logs-19-0.txt](https://github.com/airbytehq/airbyte/files/6199690/logs-19-0.txt)

**Comment by Moofasax** [comment]
I am noticing this as well on 0.17.2-alpha, when another sync happens I deleted all my pull_request, commits, etc. Probably all tables but haven't check on it.

**Comment by yeedster** [comment]
I'm wondering if this is due to the "full refresh" method of pulling in data for pull requests as opposed to "incremental"

**Comment by hoanghapham** [comment]
I have the same problems. For the tables with full refresh mode, after the the initial load, the next syncs remove all old records and leave those tables with 0 record.

**Comment by Moofasax** [comment]
Yeah i see, i guess I don't understand the point though. If we want to be able to write queries and reports for data within GitHub, why would the default be to delete all our existing data?

Is it on the roadmap to support incremental for all schemes for the GitHub connector?

**Comment by hoanghapham** [comment]
I have a feeling that this is a confusion of features between full refresh and incremental mode. 
The full refresh mode should have done these things:
- query all existing records via Github API (both old and new)
- Drop all old records in the destination DB
- Insert all new records.
However the current connection only query out the new records, while still drop all old records.

**Comment by sherifnada** [comment]
Hi everyone, I think this is a bug on our side and we are currently investigating. Will keep you all updated!

**Comment by Moofasax** [comment]
@hoanghapham ah i understand now, makes sense! and thanks @sherifnada

**Comment by sherifnada** [comment]
Hi everyone, 

could you confirm if this is happening for you on the latest version of Airbyte? We recently fixed a related bug and i want to make sure this is a separate issue. 

To upgrade Airbyte while retaining all your configuration, follow [this tutorial](https://docs.airbyte.io/tutorials/upgrading-airbyte). 

Alternatively, if you are ok losing all your Airbyte configuration, run this from the Airbyte repository root: 
	1. `docker-compose down -v`
	2. `git pull`
	3. `docker-compose up`

I just tried syncing data from Github to Postgres and I was not able to reproduce this issue. 

My versions: 

airbyte 0.18.2-alpha
github 0.2.1
postgres 0.2.3

**Comment by hoanghapham** [comment]
Hey Sherif, it works in the latest version (0.18.2)

**Comment by sherifnada** [comment]
@Moofasax @yeedster please reopen this issue if the problem persists. I believe this has been fixed on the latest version.

**Comment by hoanghapham** [comment]
@sherifnada I still encountered this issue when using the Full Refresh - Overwrite mode on the `pull_request` table. The Append mode works fine.

**Comment by Moofasax** [comment]
Hey sorry for not reporting back, yes this works for us on 0.19.0 and 0.2.2

Thanks man!

**Comment by Zirochkaa** [comment]
@hoanghapham 

Here is a connected issue #2886.
We just merged this bug into master and released a new version of the connector. 

Upgrade your connector to version `0.2.3` and get started. To upgrade your connector version, go to the admin panel in the left hand side of the UI, find this connector in the list, and input the latest connector version. 

Please let us know if you have any further questions. 

Enjoy!

**Comment by hoanghapham** [comment]
Thanks @Zirochkaa. looks like you removed the full refresh modes from the connectors?
The incremental modes work now, though still not as expected. The incremental dedup mode still produce duplicated records in the destination table

**Comment by jaorr95** [comment]
Hello, i am facing with the same problem. when i set up full refresh overwrite, the first sync save all data, the next sync delete all data on the destination and dont insert nothing. and the next sync insert all data again.

Source: github source 1.5.2
Destination: Faros destination 0.6.6 - postgres
Sync mode: Full refresh - overwrite
