### ISSUE TITLE
Orchestrator pod ignores JOB_KUBE_TOLERATIONS for itself

### ISSUE THREAD

**Issue by igsaf2** [airbytehq/airbyte#28389]
### What method are you using to run Airbyte?

Kubernetes

### Platform Version or Helm Chart Version

0.50.1

### What step the error happened?

During the Sync

### Revelant information

Setup: Kubernetes, orchestrator enabled, JOB_KUBE_TOLERATIONS set.

Behavior: sync jobs run with correct tolerations, but an orchestrator pod starts without tolerations on its pod. Env variables inside an orchestrator pod are correct.

Expected behaviour: orchestrator runs with tolerations from JOB_KUBE_TOLERATIONS env variable.

Tolerations are not set: https://github.com/airbytehq/airbyte-platform/blob/28e2339679bbb2235f3c317b6c8cd843f222092a/airbyte-commons-worker/src/main/java/io/airbyte/workers/process/AsyncOrchestratorPodProcess.java#L451C45-L451C45

**Comment by gabricc** [comment]
hello @igsaf2 , did you find a workaround for this issue? I'm facing the same here on version 0.50.33.

**Comment by Kamaradeivanov** [comment]
Same problem with v0.50.34, and no workaround yet as there is a missing `.withTolerations` part in the code mentioned by @igsaf2  : 
They should add something like the one they have done here : https://github.com/airbytehq/airbyte-platform/blob/b345eebedaed481291e7d0c6e36908649a031f51/airbyte-commons-worker/src/main/java/io/airbyte/workers/process/KubePodProcess.java#L585

**Comment by gabricc** [comment]
I've deployed Airbyte again now with 0.53.196 and this time the tolerations were properly added to the orchestrator pods! 🙌🏻🚀

**Comment by daniel-ro** [comment]
@igsaf2 
did you find a way to workaround this? looks like the tolerations are not being added to the orchestration pod and it's not fixed in `0.53.196`

**Comment by SampaioLeal** [comment]
any updates or workarounds?

**Comment by brianbolt** [comment]
I am facing the same outcome with a new version helm chart `0.442.3` (AIrbyte 0.67.17).  Orchestrator pods cannot be scheduled because the tolerations are not passed to the pod.

WIth this yaml:
```
global:
  jobs:
    kube:
      nodeSelector:
        "disco/node-type": "jobs-node"
      tolerations:
        - key: "airbyte-jobs"
          operator: "Exists"
          effect: "NoSchedule"
```

When the pod spins up the tolerations have the following (missing the `airbyte-jobs` key):


```
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
```

The node selecter however is passed to the orchestrator pod:


```
  nodeSelector:
    disco/node-type: jobs-node
 ```
 
 This causes the pod to not get scheduled with the following error:
 
 ```
0/4 nodes are available: 1 node(s) had untolerated taint {airbyte-jobs: true}, 3 node(s) didn't match Pod's node affinity/selector. preemption: 0/4 nodes are available: 4 Preemption is not helpful for scheduling
  ```

**Comment by yogevx** [comment]
@brianbolt  +1
I'm encountering the same issue with the latest version.
The orchestrator pods are not respecting the specified tolerations, which prevents them from being scheduled correctly.

**Comment by kevogabaa** [comment]
> I am facing the same outcome with a new version helm chart `0.442.3` (AIrbyte 0.67.17). Orchestrator pods cannot be scheduled because the tolerations are not passed to the pod.
> 
> WIth this yaml:
> 
> ```
> global:
>   jobs:
>     kube:
>       nodeSelector:
>         "disco/node-type": "jobs-node"
>       tolerations:
>         - key: "airbyte-jobs"
>           operator: "Exists"
>           effect: "NoSchedule"
> ```
> 
> When the pod spins up the tolerations have the following (missing the `airbyte-jobs` key):
> 
> ```
>   tolerations:
>   - effect: NoExecute
>     key: node.kubernetes.io/not-ready
>     operator: Exists
>     tolerationSeconds: 300
>   - effect: NoExecute
>     key: node.kubernetes.io/unreachable
>     operator: Exists
>     tolerationSeconds: 300
> ```
> 
> The node selecter however is passed to the orchestrator pod:
> 
> ```
>   nodeSelector:
>     disco/node-type: jobs-node
> ```
> 
> This causes the pod to not get scheduled with the following error:
> 
> ```
> 0/4 nodes are available: 1 node(s) had untolerated taint {airbyte-jobs: true}, 3 node(s) didn't match Pod's node affinity/selector. preemption: 0/4 nodes are available: 4 Preemption is not helpful for scheduling
> ```

I am having a similar issue but my helm version is the latest as of today, 0.493.1 and app version 0.64.0

**Comment by alexremn** [comment]
Have the same with 0.64.1 (latest).

**Comment by brianbolt** [comment]
This works for me as suggested on [this slack thread](https://airbytehq.slack.com/archives/C021JANJ6TY/p1725617958548289?thread_ts=1723735183.126089&cid=C021JANJ6TY)


Additionally add:

```
worker:  
   extraEnv:
    - name: JOB_KUBE_TOLERATIONS
      value: "key=airbyte-jobs,operator=Exists,effect=NoSchedule"
```

After that, my Airbyte source had this added to it's specification when it was spun up:

```
  tolerations:
  - effect: NoSchedule
    key: airbyte-jobs
    operator: Exists
```

**Comment by alexremn** [comment]
Still no tolerations in 0.64.3.

@marcosmarxm can you please take a look?

Seems like related to absence of toleration spec [here](https://github.com/airbytehq/airbyte-platform/blob/main/airbyte-workload-launcher/src/main/kotlin/pods/factories/OrchestratorPodFactory.kt) (im not a kotlin dev, so could be wrong).

This bug is weird, as we are using airbyte in dynamic environment and to eliminate issues with orchestrator/connectors pods timeouts due to node spin up + pod spin up we added static nodes and pointed workload to static nodes through node_selector + tolerations, but absence of tolerations on orchestrator breaks this idea.

**Comment by andrevus** [comment]
There is a workaround available using a Kyverno policy that automatically adds the required Tolerations to Pods based on conditions such as labels or namespaces. This ensures the correct Tolerations are applied without needing to modify every Pod manifest manually. However, I’m still waiting for a fix from the Airbyte team to address the issue directly. Here’s an example of the Kyverno policy:

`
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-default-tolerations-airbyte
spec:
  rules:
    - name: add-tolerations-if-not-exist
      match:
        resources:
          kinds:
            - Pod
          namespaces:
            - airbyte
      preconditions:
        all:
          - key: "{{ request.object.metadata.labels.sync_step || '' }}"
            operator: Equals
            value: "orchestrator-replication"
      mutate:
        patchStrategicMerge:
          spec:
            tolerations:
              - key: "example-key"
                operator: "Exists"
                effect: "NoSchedule"

`

**Comment by andrevus** [comment]
There is a workaround available using a Kyverno policy that automatically adds the required Tolerations to Pods based on conditions such as labels or namespaces. This ensures the correct Tolerations are applied without needing to modify every Pod manifest manually. However, I’m still waiting for a fix from the Airbyte team to address the issue directly. Here’s an example of the Kyverno policy:
```
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-default-tolerations-airbyte
spec:
  rules:
    - name: add-tolerations-if-not-exist
      match:
        resources:
          kinds:
            - Pod
          namespaces:
            - airbyte
      preconditions:
        all:
          - key: "{{ request.object.metadata.labels.sync_step || '' }}"
            operator: Equals
            value: "orchestrator-replication"
      mutate:
        patchStrategicMerge:
          spec:
            tolerations:
              - key: "example-key"
                operator: "Exists"
                effect: "NoSchedule"
```

**Comment by alexremn** [comment]
Just for reference:
0.64.4 - still no fix. :D

Airbyte changed replication strategy to all-in-one pod as i see, so if you're using kyverno - change label value from `orchestrator-replication` to `replication`.

**Comment by marcosmarxm** [comment]
I raised this to the deployment team. Sorry the long delay to get this solved!

**Comment by desperguin** [comment]
Hi! we have the same problem, we could use dedicated nodes on k8s for this reason. There is any news?
We can use the kyverno workarround.
thanks!!

**Comment by mirobertod** [comment]
Same issue here

**Comment by Iliabuleh** [comment]
Same here, Chart version 1.0.0

**Comment by matheusnd** [comment]
Same here, Chart version 1.0.0

**Comment by abuchanan-airbyte** [comment]
This may have been fixed by https://github.com/airbytehq/airbyte-platform/commit/2ed01e554d576bd60011583ea988aeac8980f2f0

**Comment by alexremn** [comment]
1.1.0 - still there.
@abuchanan-airbyte according to roadmap, which version will contain this fix?

**Comment by GideonStowell** [comment]
Based on this [source](https://docs.airbyte.com/release_notes/v-1.0#airbyte-v100) it seems like Airbyte will be shipping new releases every month. This would suggest that the next release will be available the last week of October 2024.

**Comment by mickutz** [comment]
bumping this as we've run into the exact same issue whilst attempting to migrate from the compose based deployment into kube
:crossed_fingers:

**Comment by amardatar** [comment]
Tried this with image tag `nightly-1729465575-0d9339a006` and it looks like it's working now (earlier tags are probably fine as well, only tried the latest one)

**Comment by amardatar** [comment]
@JuninhoFreitas not changing the version, just the image tag being used, ie:

```yaml
global:
  image:
    tag: nightly-1729465575-0d9339a006
  ...
```

This is only really for testing anyway if you're comfortable, and to back up what @GideonStowell said - it looks like this should be resolved in the next official release (hopefully coming soon).

**Comment by dimisjim** [comment]
@amardatar did you try with a newly created cluster with helm or via a helm upgrade?

**Comment by amardatar** [comment]
@dimisjim a helm upgrade

**Comment by brentonmorris** [comment]
I am attempting to use this to set the tolerations for the provisioner:
https://github.com/airbytehq/airbyte-platform/blob/main/charts/airbyte/values.yaml#L965-L969

Is this the correct way to get `tolerations` and `nodeSelector` specs onto the job pods that workload-launcher creates?

I must not be getting the format of my string correctly. I get this error:

```
Error: cannot patch "airbyte-workload-launcher" with kind Deployment: Deployment.apps "airbyte-workload-launcher" is invalid: spec.template.spec.containers[0].env[29].valueFrom: Invalid value: "": may not be specified when `value` is not empty
```

The data I am passing to `extraEnv`:
```
extraEnv = [
  {
    name  = "JOB_KUBE_TOLERATIONS"
    value = "effect=NoExecute,key=node_type,value=worker;effect=NoExecute,key=provisioner,value=${local.cluster_provisioner_name}"
  }
]
```

Does anyone know if this is supposed to add `tolerances` and `nodeSelector` to the job pods provisioned by workload-launcher?

**Comment by amardatar** [comment]
@brentonmorris I'm doing it via global.jobs.kube in the helm chart instead, like this:

```yaml
global:
  jobs:
    kube:
      nodeSelector:
        {key}: {value}
      tolerations:
        - key: {key}
          operator: Equal
          value: {value}
          effect: NoSchedule
```

Which seems to be working - I haven't tried using `extraEnv` (although I vaguely remember seeing it so maybe it should work).

**Comment by brentonmorris** [comment]
> [@brentonmorris](https://github.com/brentonmorris) I'm doing it via global.jobs.kube in the helm chart instead, like this:
> 
> global:
>   jobs:
>     kube:
>       nodeSelector:
>         {key}: {value}
>       tolerations:
>         - key: {key}
>           operator: Equal
>           value: {value}
>           effect: NoSchedule
> Which seems to be working - I haven't tried using `extraEnv` (although I vaguely remember seeing it so maybe it should work).

I have set those as well. The issue for me is with the pods that the `airbyte-workload-launcher` deployment spins up when a job is run.

Those pods don't end up having the tolerations that I've set in either of those places, so my k8s provisioner doesn't pick them up and they don't get provisioned at all because the tolerations don't match with any node group.

I can see that the `postgres-check` pod doesn't have the tolerations applied.

This seems like a straightforward thing one would want to do, but that `airbyte-workload-laucher` just seems like it doesn't want to add my tolerations that I've set. I was hoping I am just doing something wrong, but I think I've tried about everything I can think of.

As of now, we can't use Airbyte on our infrastructure because of this.

**Comment by AcidFlow** [comment]
Hello!

We are running into the same issue, as previously described it happens on v1.1.0 and using the nightly build indeed propagates the value correctly.

Looking at the diff between main and v1.1.0, I think the commit that fixes the issue is the following one:

https://github.com/airbytehq/airbyte-platform/commit/2ca3c4192793b15a1ccc2bfd644dd725c3a2903c#diff-3555dc77946bb010495d4a97b3060553f759452f781e0f5b54b3c8a37394c3b0R227

**Comment by alexremn** [comment]
This is fixed in 1.2.0

**Comment by marcosmarxm** [comment]
@abuchanan-airbyte can we close this?

**Comment by bmschow** [comment]
This does not seem to be fixed.  1.2.0 is still not pulling tolerations for sync workers

**Comment by bmschow** [comment]
This does not seem to be fixed.  1.2.0 is still not pulling tolerations for sync workers
