### ISSUE TITLE
Airbyte not starting

### ISSUE THREAD

**Issue by tfrazer-remine** [airbytehq/airbyte#28469]
### What method are you using to run Airbyte?

Docker

### Platform Version or Helm Chart Version

0.50.8

### What step the error happened?

On deploy

### Revelant information

We have tried to deploy Airbyte on an EC2 instance running Ubuntu 22.04, but the startup script `run-ab-platform.sh` just runs forever on a loop. All docker container logs are attached.

This is in regards to the ZenDesk ticket #361.
[airbyte-connector-builder-server.txt](https://github.com/airbytehq/airbyte/files/12095767/airbyte-connector-builder-server.txt)
[Uploading airbyte-cron.txt…]()

[airbyte-worker.txt](https://github.com/airbytehq/airbyte/files/12
[airbyte-temporal.txt](https://github.com/airbytehq/airbyte/files/1
[airbyte-proxy.txt](https://github.com/airbytehq/airbyte/files/12095761/airbyte-proxy.txt)
2095754/airbyte-temporal.txt)
[airbyte-db.txt](https://github.com/airbytehq/airbyte/files/12095764/airbyte-db.txt)

[airbyte-server.txt](https://github.com/airbytehq/airbyte/files/12095758/airbyte-server.txt)

[airbyte-webapp.txt](https://github.com/airbytehq/airbyte/files/12095752/airbyte-webapp.txt)
095749/airbyte-worker.txt)

**Comment by ricardo-lobo** [comment]
In my case the `./temporal/dynamicconfig/development.yaml` was missing

when the service airbyte-temporal was trying to start it kept reporting this error.

I fixed this by getting the missing file directly from here https://github.com/airbytehq/airbyte-platform/blob/main/temporal/dynamicconfig/development.yaml

**Comment by tfrazer-remine** [comment]
./temporal/dynamicconfig/development.yaml was missing. I added it, but Airbyte is still not starting. New logs are attached below.

[airbyte-connector-builder-server.txt](https://github.com/airbytehq/airbyte/files/12099576/airbyte-connector-builder-server.txt)
[airbyte-cron.txt](https://github.com/airbytehq/airbyte/files/12099579/airbyte-cron.txt)
[airbyte-db.txt](https://github.com/airbytehq/airbyte/files/12099580/airbyte-db.txt)
[airbyte-proxy.txt](https://github.com/airbytehq/airbyte/files/12099582/airbyte-proxy.txt)
[airbyte-server.txt](https://github.com/airbytehq/airbyte/files/12099583/airbyte-server.txt)
[airbyte-temporal.txt](https://github.com/airbytehq/airbyte/files/12099584/airbyte-temporal.txt)
[airbyte-webapp.txt](https://github.com/airbytehq/airbyte/files/12099585/airbyte-webapp.txt)
[airbyte-worker.txt](https://github.com/airbytehq/airbyte/files/12099587/airbyte-worker.txt)

**Comment by quentin-js** [comment]
@ricardo-lobo solution worked for me too, thanks!

**Comment by nahdaveiga** [comment]
> In my case the `./temporal/dynamicconfig/development.yaml` was missing
> 
> when the service airbyte-temporal was trying to start it kept reporting this error.
> 
> I fixed this by getting the missing file directly from here https://github.com/airbytehq/airbyte-platform/blob/main/temporal/dynamicconfig/development.yaml

Hi, It worked for me!

**Comment by cpdeethree** [comment]
Hi, can we confirm this issue is now resolved? We pushed an update to run-ab-platform.sh that now pulls this file

**Comment by tfrazer-remine** [comment]
@cpdeethree yes this issue is now resolved.
