### ISSUE TITLE
Experience to upgrade Airbyte version should be more discoverable and easier from the UI

### ISSUE THREAD

**Issue by johnlafleur** [airbytehq/airbyte#3003]
## Tell us about the problem you're trying to solve
It seems most users don't upgrade to the latest version (cf. https://analytics.amplitude.com/daxtarity/chart/guwgsmc?source=redirect%3A+chart+saved). For instance, after a week, only 35% of users upgraded to the latest version. 
And 40% of users haven't upgraded their Airbyte version for a month, while still using it today. 

## Describe the solution you’d like
Make it both more visible that a new version is available and easy to upgrade. 

A note here: this only concerns the open-source edition (and won't matter for the hosted solution)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368103089287) by [Unito](https://www.unito.io)

**Comment by johnlafleur** [comment]
Here's a suggestion of design for it: https://www.figma.com/file/AODY4oi15iI5l0fbxHvobt/Daxtarity?node-id=24813%3A132165
@cgardens

**Comment by michel-tricot** [comment]
The mockup looks good. Just setting expectation though: pressing upgrade will open the documentation.

I would be find if we make the message not dismissable or if dismissable then it comes back at least once a day

**Comment by johnlafleur** [comment]
I'm okay with once a day. I feel it's a bit pushy, but if we want to increase the conversion to upgrading, this is what needs to be done.

**Comment by marcosmarxm** [comment]
@johnlafleur what do you think to create a main page displaying => next sync scheduled, some basic analytics to the user AND a list showing when some user source need to be upgraded Airbyte version and source/destination? Having a main page with useful information to users can be a nice place to help interact with them. Sorry my mock whats the first I founded for free :art: 
![image](https://user-images.githubusercontent.com/5154322/115964807-8a10c200-a4fc-11eb-8aaf-f1992848b285.png)

**Comment by johnlafleur** [comment]
A home page could definitely help indeed. But it would also need a lot more time to think about as we want to display the right information there. I feel we can address the problem addressed by the issue with some first intermediary steps, before having a home page.

**Comment by johnlafleur** [comment]
In Figma, we had the idea to build a left section that could be dedicated to updates. 
But I'm wondering if we shouldn't leverage a tool for that, such as https://www.getbeamer.com/
This tool could enable us to get NPS, feature upvote, etc.
And this goes beyond this simple task. I think we need to have a discussion on that topic. 
Wdyt @avaidyanatha @nataliekwong ?

**Comment by avaidyanatha** [comment]
Can you clarify on this - would Beamer completely replace the updates section? I feel like we should still have a static place for all the information instead of just a pop up on releases.

**Comment by cgardens** [comment]
@Jamakase can we add the following button in the app ("Update" -- see screenshot below. Let's go with "Update" instead of "Updates".)

![Screen Shot 2021-06-24 at 12 51 53 PM](https://user-images.githubusercontent.com/9092207/123323860-f56e1480-d4ea-11eb-9e17-2de88baa1374.png)

## Must Have:
This button should open a new tab and link to `https://docs.airbyte.io/upgrading-airbyte`.

## Nice to have:
This button only appears when there is a new version of Airbyte available. This would be determined by fetching this file from github https://github.com/airbytehq/airbyte/blob/master/.env and comparing the `VERSION` variable to whatever version the webapp is running on. If the version on github is greatr than the button should appear (with a a red dot, like we do for the admin page). 

You can find the logic for how we do the version comparison in java [here](https://github.com/airbytehq/airbyte/blob/master/airbyte-commons/src/main/java/io/airbyte/commons/version/AirbyteVersion.java#L93-L106); it might be a useful reference as you will likely need something similar in javascript.

@Jamakase lmk if the "nice to have" section feels reasonable to you.

**Comment by cgardens** [comment]
will move forward with the platform upgrade button on this issue(https://github.com/airbytehq/airbyte/issues/3673)

**Comment by johnlafleur** [comment]
@avaidyanatha sorry I didn't see your message. It would replace the Updates section in the web app indeed. It would included upgrade buttons that would redirect you to the upgrade section in the docs. The good thing with Beamer is that we can notify you about new features right from the app, and I suspect with Airbyte Cloud most users won't go to the docs for changelog information. 

Right now, the Updates button in the left column opens https://docs.airbyte.io/operator-guides/upgrading-airbyte , which doesn't make sense.

**Comment by natikgadzhi** [comment]
@bgroff @malikdiarra should we close this? /shrug
