### ISSUE TITLE
testConvertMongoDbChangeEvent is failing

### ISSUE THREAD

**Issue by postamar** [airbytehq/airbyte#31032]
### Relevant information

Since https://github.com/airbytehq/airbyte/pull/29969 merged, `testConvertMongoDbChangeEvent` in the java CDK's `db-sources` has been failing

**Comment by jdpgrailsdev** [comment]
This has been resolved by https://github.com/airbytehq/airbyte/pull/29969

**Comment by jdpgrailsdev** [comment]
The fix has been merged and verified

**Comment by postamar** [comment]
It's still failing on my machine, this time it's something to do with timezones, the timestamp field is 3 hours off on my machine.
