### ISSUE TITLE
Slack source is not including most thread data

### ISSUE THREAD

**Issue by chandlerprall** [airbytehq/airbyte#32143]
### Connector Name

source-slack

### Connector Version

0.3.5

### What step the error happened?

Other

### Relevant information

I created a slack source in airbyte cloud, authorized with oAuth, and pointed it at various non-private channels starting at 2023-01-01, with a thread lookback window of 30 days (have tried with lookback values from 0 - 365). Only some thread content is retrieved.

I have 350 total messages with 1+ replies since 2023-10-01,
```sql
select count(1), channels.name from slack.channel_messages join slack.channels on channels.id = channel_id where reply_count > 0 and float_ts >= 1696118400 group by channels.name; -- 350 total
```

<details>
<summary>Results</summary>

|  f0_  |           name            |
|-------|---------------------------|
|   83  |   dev-platform-move       |
|   40  |   oncall                  |
|   12  |   design                  |
|   91  |   proj-user-management    |
|   28  |   dev-platform-compose    |
|   4   |   proj-stream-centric-ux  |
|   21  |   dev-frontend            |
|   14  |   dev-platform            |
|   11  |   local-dev-environment   |
|   27  |   dev                     |
|   19  |   notes-and-user-feedback |
</details>

but only 96 threads, many of which appear to have been reassigned to a different channel
```sql
select count(distinct thread_ts), channels.name from slack.threads join slack.channels on channels.id = channel_id group by channels.name; -- 96 total
```

<details>
<summary>Results</summary>

|  f0_  |           name            |
|-------|---------------------------|
|   81  |   dev-platform            |
|    3  |   oncall                  |
|    1  |   design                  |
|    3  |   proj-user-management    |
|    3  |   dev                     |
|    3  |   dev-platform-move       |
|    1  |   local-dev-environment   |
|    0  |   dev-frontend            |
|    1  |   dev-platform-compose    |
</details>

and even when I have a thread, it is sometimes missing posts entirely and many entires have a `null` value in _thread_ts_

```sql
with threads as (select distinct thread_ts as ts, count(1) as count from slack.threads group by thread_ts)
select t.ts, t.count, cm.reply_count from threads t left join slack.channel_messages cm on cm.ts = t.ts;
```

<details>
<summary>Results</summary>

|        ts        | count | reply_count |
|------------------|-------|-------------|
|                  |   45  |             |
| 1698862747.924949 |   4  |      2      |
| 1698782547.684469 |  17  |     27      |
| 1698784219.088569 |   1  |             |
| 1698257649.616659 |   6  |      9      |
| 1673042942.984629 |   2  |      1      |
| 1673556116.795519 |  11  |     10      |
| 1674224433.484119 |  61  |     89      |
| 1674214631.993809 |   1  |     16      |
| 1674515647.354159 |   4  |      3      |
| 1674510958.844179 |  32  |     37      |
| 1678728037.702559 |  11  |     10      |
| 1678822536.562499 |   2  |      1      |
| 1678913951.448259 |  15  |     14      |
| 1679095842.319729 |  19  |     18      |
| 1679332904.147659 |   2  |      1      |
| 1679436138.904739 |   2  |      1      |
| 1679515840.083329 |   8  |      7      |
| 1680737222.075019 |   5  |      5      |
| 1681201225.566759 |   2  |      1      |
| 1681338197.648119 |   3  |      2      |
| 1681477185.124819 |   3  |      2      |
| 1681751844.532969 |   4  |      3      |
| 1681851649.928039 |   9  |      8      |
| 1681845763.478519 |   1  |      3      |
| 1681841055.693299 |  16  |     29      |
| 1681837437.645679 |  10  |     10      |
| 1682438999.720179 |   3  |     17      |
| 1682633198.686089 |  17  |     16      |
| 1682721353.510919 |  17  |     16      |
| 1683566317.446299 |   2  |      1      |
| 1683564037.789979 |  10  |     16      |
| 1683658992.051939 |   1  |     12      |
| 1683920895.892639 |  26  |     25      |
| 1684190981.024209 |  37  |     36      |
| 1684370668.994449 |   2  |      5      |
| 1684513241.539529 |   1  |      1      |
| 1685036393.140989 |   1  |      5      |
| 1685131682.577829 |   7  |      6      |
| 1685461510.207029 |   4  |      3      |
| 1685642669.606639 |   7  |      7      |
| 1686065997.424219 |   3  |      2      |
| 1686163182.486129 |   6  |      5      |
| 1686252395.708859 |  11  |     10      |
| 1686321925.468399 |   7  |      6      |
| 1686606732.806429 |   7  |      6      |
| 1686590445.042189 |   6  |      7      |
| 1689199347.721149 |  14  |     13      |
| 1689124114.899789 |   1  |      2      |
| 1689632431.950529 |   8  |      7      |
| 1689694976.837119 |   2  |      1      |
| 1689817975.168839 |   1  |      3      |
| 1689975245.619179 |   6  |      5      |
| 1690212963.859479 |  99  |    105      |
| 1690312164.813769 |  17  |     16      |
| 1690306190.386029 |   8  |     11      |
| 1690824338.987139 |   1  |     35      |
| 1690911773.729509 |   4  |     30      |
| 1690989099.766509 |   4  |      4      |
| 1691536761.721739 |   8  |      7      |
| 1692030175.490119 |   4  |      4      |
| 1692302475.835959 |   6  |      5      |
| 1692628621.099409 |  11  |     10      |
| 1692685047.499689 |   5  |      4      |
| 1692752990.303169 |  11  |     10      |
| 1693250678.844019 |   8  |      7      |
| 1693348422.368229 |   5  |      4      |
| 1693329177.995819 |   6  |     10      |
| 1694701899.311969 |  12  |     17      |
| 1695078482.574839 |  24  |     23      |
| 1695245423.723029 |   8  |     10      |
| 1695324192.381619 |   6  |      5      |
| 1695315537.022109 |  30  |     83      |
| 1695254943.510509 |   1  |      6      |
| 1695734565.463999 |   5  |      4      |
| 1696016412.976919 | 110  |    117      |
| 1696283499.007929 |   2  |      1      |
| 1696441629.043269 |  73  |     72      |
| 1697154437.568239 |   8  |      7      |
| 1697154114.112389 |  35  |     35      |
| 1697406131.647869 |  18  |     17      |
| 1697759952.582259 |   3  |      2      |
| 1697818206.711129 |  20  |     28      |
| 1698108145.274449 |   2  |      2      |
| 1698404293.606289 |  24  |     23      |
| 1698783038.366509 |   4  |      3      |
| 1698773403.114189 |   3  |     32      |
| 1698789494.198589 |   4  |      3      |
| 1698969040.284779 |   2  |      1      |
| 1698286772.214739 |   2  |     27      |
| 1698789455.958869 |   1  |             |
| 1698885393.346759 |   1  |      1      |
| 1698885489.340929 |   2  |             |
| 1698929382.997029 |   5  |      4      |
| 1698946374.907879 |   2  |      1      |
| 1698954598.960039 |   2  |      2      |
| 1698938322.004539 |   1  |      1      |
</details>

### Contribute

- [ ] Yes, I want to contribute

**Comment by katmarkham** [comment]
https://api.slack.com/changelog/2020-01-deprecating-antecedents-to-the-conversations-api

**Comment by davydov-d** [comment]
hey @chandlerprall can you please share the link to your cloud connection?

**Comment by chandlerprall** [comment]
@davydov-d https://cloud.airbyte.com/workspaces/f2442b0e-6e85-40fb-89a0-1b8870d9c91b/connections/c301dfa2-d577-49b2-8b86-8500350bba89/status

**Comment by davydov-d** [comment]
https://github.com/airbytehq/airbyte/pull/32707 - in review

**Comment by lazebnyi** [comment]
@chandlerprall Can you check again with last version, PR with fix merged - https://github.com/airbytehq/airbyte/pull/32707

**Comment by chandlerprall** [comment]
I've reset my connection and am re-running the sync. I'll update again when the data is available and I can take a look through the results

**Comment by chandlerprall** [comment]
I'm still missing a _lot_ of thread data. With a start of `2023-01-01T00:00:00Z` and 365 day lookback window:

sum of `channel_messages.reply_count` by channel,

<details>
<summary>channel messages sql</summary>
select
  c.name as channel,
  sum(reply_count) as reply_count_sum
from slack.channel_messages cm
join slack.channels c on c.id = cm.channel_id
group by c.name;
</details>

| Channel                     | Reply Count Sum |
|-----------------------------|-----------------|
| dev                         | 2356            |
| dev-frontend                | 2049            |
| dev-platform                | 2437            |
| dev-platform-compose        | 3522            |
| design                      | 202             |
| local-dev-environment       | 1272            |
| notes-and-user-feedback     | 1475            |
| oncall                      | 5154            |
| proj-connection-flow-ux     | 113             |
| proj-stream-centric-ux      | 745             |
| proj-user-management        | 2107            |
| dev-platform-move           | 6726            |

And counting non-parent thread messages by channel, (including parent messages finds 43 more in dev-platform)

<details>
<summary>threads sql</summary>
select
  c.name as channel,
  count(1) as thread_messages_count
from slack.threads t
join slack.channels c on c.id = t.channel_id
where t.thread_ts is not null
group by c.name;
</details>

| Channel               | Thread Messages Count |
|-----------------------|-----------------------|
| dev-platform          | 1035                  |
| dev-platform-move     | 14                    |

**Comment by chandlerprall** [comment]
Wow, nice find @hugovandernotte !

after performing resets,
channel_messages full refresh + threads full refresh: yields data
channel_messages incremental + threads full refresh: yields data
channel_messages full refresh + threads incremental: is affected
channel_messages incremental + threads incremental: yields data

looks like issue is present when `threads` stream is incremental

**Comment by darynaishchenko** [comment]
https://github.com/airbytehq/airbyte/pull/32707 pr was merged into master, @chandlerprall  could please verify your data and let me know the results.

**Comment by chandlerprall** [comment]
Hey hey! Now that my cloud source is on 0.3.6 the data is coming through as I expect 🚀

Tested with a full reset then a sync with `channel_messages` and `threads` in incremental | append

**Comment by isidduhussain** [comment]
@chandlerprall  I am trying to evaluate Airbyte for Slack and other SAAS data pipelines, but I see it is very slow with Slack it is taking approximately 6 hours for 1900 records out of which 583 are full sync records of users, channels, and members. I am curious if you were able to see the same results or if were you able to extract high-volume data. 

Your feedback is appreciated. This is my sync history 

![image](https://github.com/airbytehq/airbyte/assets/50725326/0218f426-463e-4b3d-a322-187abd7ac2b8)

**Comment by chandlerprall** [comment]
@isidduhussain I'm seeing consistent 10-15 minute runs for my slack source, yielding 6.5MB across 7500 records

**Comment by isidduhussain** [comment]
@chandlerprall do you include Threads for sync?

**Comment by chandlerprall** [comment]
@isidduhussain yes I do, my stream configuration is:

| stream | sync mode|
|---|---|
| channel_members | Incremental, Append |
| channels | Full refresh, Overwrite |
| threads | Incremental, Append |
| users | Full refresh, Overwrite |

both incremental streams use `float_ts` for the cursor
