### ISSUE TITLE
[source-facebook-marketing] Nonexisting field (cost_per_conversion_lead) on node type (AdsInsights)

### ISSUE THREAD

**Issue by tomaszwija** [airbytehq/airbyte#38835]
### Connector Name

source-facebook-marketing

### Connector Version

3.0.0

### What step the error happened?

During the sync

### Relevant information

AdsInsights sync fails, looks like the cost_per_conversion_lead field was dropped from the marketing API?
Even though it's still in the sdk 
https://github.com/facebook/facebook-python-business-sdk/blob/063d440823be6fcbe9b1e3e6562a477c4baf0eb6/facebook_business/adobjects/adsinsights.py#L69

I cannot find the reference to this field here:
https://developers.facebook.com/docs/marketing-api/reference/ads-insights/?locale=en_US

### Relevant log output

```shell
Response:
    {
      "error": {
        "message": "(#100) Tried accessing nonexisting field (cost_per_conversion_lead) on node type (AdsInsights)",
        [...]
      }
    })
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by MoralesPablo** [comment]
Same problem here!!

**Comment by pKorsholm** [comment]
Same problem here!

**Comment by aaronsteers** [comment]
This was also recently reported by a PyAirbyte user. Confirmed that the connector doesn't have any recent releases that this would be attributed to.

**Comment by intelc** [comment]
same problem for us!

**Comment by intelc** [comment]
> released

we are still using pre- 3.0 version and still affected by this issue

**Comment by tomaszwija** [comment]
Looks like conversion_lead_rate field was also removed from the api. 
When I removed references to cost_per_conversion_lead sync still fails for conversion_lead_rate.
With those two fields removed from:

- airbyte-integrations/connectors/source-facebook-marketing/integration_tests/spec.json
- airbyte-integrations/connectors/source-facebook-marketing/unit_tests/integration/test_ads_insights_action_product_id.py
- airbyte-integrations/connectors/source-facebook-marketing/source_facebook_marketing/schemas/ads_insights.json

sync works fine.

**Comment by Johnsonwang1** [comment]
I also encountered this error in airbyte cloud, this problem has been going on for two days, isn't there anyone official to fix it?

**Comment by miki-dd** [comment]
Same here we're unable to sync any Facebook data

**Comment by khoadaniel** [comment]
Same problem here? Any official solution for this?
Thank you.

**Comment by VicSrt** [comment]
Same problem here.

**Comment by kobzevvv** [comment]
same

**Comment by citizen-seven** [comment]
We're Airbyte cloud customers and had a chat with support, Airbyte team looks into this and plans to ship update ASAP (hopefully till the end of the date today)

**Comment by recruz02** [comment]
My team is also experiencing this issue. Hoping this gets resolved as soon as possible as this completely killed our facebook conn. Thanks all

**Comment by bazarnov** [comment]
We're working on the fix now, this is the top priority for us, stay tuned.

**Comment by nathaniellx1** [comment]
My team also has same issue! Thanks for looking into this :)

**Comment by tybernstein** [comment]
The [fix has been deployed ](https://github.com/airbytehq/airbyte/pull/38860)on version 3.1.0 of the Facebook Marketing Source Connector!

**Comment by khoadaniel** [comment]
Hi @tybernstein ,

Thanks for the update.

➡️ I've upgraded the connector to version 3.1.0 and reran the process without resetting, but unfortunately, it still failed ⚠️ .

Could you suggest any alternatives that don't involve resetting the data? Resetting isn't feasible for us as it would lead to a loss of historical data, and there's no assurance that a full refresh would successfully reload all production data.

Thanks.

[Source.](https://docs.airbyte.com/integrations/sources/facebook-marketing-migrations?_gl=1*9lpksw*_gcl_au*MTMwODA0OTU0MS4xNzE2MjkzODE3#3.0.0)
![image](https://github.com/airbytehq/airbyte/assets/84840546/627bd8bd-21f9-490b-97f8-5b241fe43aa5)

**Comment by bazarnov** [comment]
@khoadaniel @tybernstein

The alternative is (customer's side):
1) `Backup` the data for the affected table (stream) to the `tmp table` (customer's side): table `A`
2) `Reset` and `re-sync` the affected table (stream): table `B`
3)  Merge `A` and `B` together

Unfortunately, there are no alternatives after this change from the source-side perspective, if there were some, we probably have done that already, without the breaking change.

**Comment by khoadaniel** [comment]
Hi @maxi297 ,

The error is the same as the one before the upgrade to 3.1.0.

🙏 Thanks for your help.


```
2024-06-03 22:22:45 platform > failures: [ {
  "failureOrigin" : "source",
  "failureType" : "system_error",
  "internalMessage" : "(#100) Tried accessing nonexisting field (cost_per_conversion_lead) on node type (AdsInsights)",
  "externalMessage" : "Error: 100, (#100) Tried accessing nonexisting field (cost_per_conversion_lead) on node type (AdsInsights).",
  "metadata" : {
    "attemptNumber" : 4,
    "jobId" : 55473,
    "from_trace_message" : true,
    "connector_command" : "read"
  },
  "stacktrace" : "Traceback (most recent call last):\n  File \"/airbyte/integration_code/source_facebook_marketing/streams/base_insight_streams.py\", line 131, in read_records\n    for obj in job.get_result():\n  File \"/usr/local/lib/python3.9/site-packages/backoff/_sync.py\", line 105, in retry\n    ret = target(*args, **kwargs)\n  File \"/airbyte/integration_code/source_facebook_marketing/streams/async_job.py\", line 379, in get_result\n    return self._job.get_result(params={\"limit\": self.page_size})\n  File \"/usr/local/lib/python3.9/site-packages/facebook_business/adobjects/helpers/adreportrunmixin.py\", line 14, in get_result\n    return self.get_insights(fields=fields, params=params)\n  File \"/usr/local/lib/python3.9/site-packages/facebook_business/adobjects/adreportrun.py\", line 139, in get_insights\n    return request.execute()\n  File \"/usr/local/lib/python3.9/site-packages/facebook_business/api.py\", line 663, in execute\n    cursor.load_next_page()\n  File \"/airbyte/integration_code/source_facebook_marketing/streams/patches.py\", line 40, in load_next_page\n    response_obj = self._api.call(\n  File \"/usr/local/lib/python3.9/site-packages/backoff/_sync.py\", line 105, in retry\n    ret = target(*args, **kwargs)\n  File \"/airbyte/integration_code/source_facebook_marketing/api.py\", line 169, in call\n    response = super().call(method, path, params, headers, files, url_override, api_version)\n  File \"/usr/local/lib/python3.9/site-packages/facebook_business/api.py\", line 336, in call\n    raise fb_response.error()\nfacebook_business.exceptions.FacebookRequestError: \n\n  Message: Call was not successful\n  Method:  GET\n  Path:    https://graph.facebook.com/v19.0/3752604365018271/insights\n  Params:  {'limit': 100}\n\n  Status:  400\n  Response:\n    {\n      \"error\": {\n        \"message\": \"(#100) Tried accessing nonexisting field (cost_per_conversion_lead) on node type (AdsInsights)\",\n        \"type\": \"OAuthException\",\n        \"code\": 100,\n        \"fbtrace_id\": \"A9bZcnBA87gnfN5ZtVS0Ket\"\n      }\n    }\n\n",
  "timestamp" : 1717453363831,
  "streamDescriptor" : {
    "name" : "ads_insights"
  }
}, {
  "failureOrigin" : "source",
  "failureType" : "config_error",
  "externalMessage" : "During the sync, the following streams did not sync successfully: ads_insights: AirbyteTracedException('(#100) Tried accessing nonexisting field (cost_per_conversion_lead) on node type (AdsInsights)')",
  "metadata" : {
    "attemptNumber" : 4,
    "jobId" : 55473,
    "from_trace_message" : true,
    "connector_command" : "read"
  },
  "stacktrace" : "Traceback (most recent call last):\n  File \"/airbyte/integration_code/main.py\", line 9, in <module>\n    run()\n  File \"/airbyte/integration_code/source_facebook_marketing/run.py\", line 18, in run\n    launch(source, sys.argv[1:])\n  File \"/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py\", line 234, in launch\n    for message in source_entrypoint.run(parsed_args):\n  File \"/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py\", line 122, in run\n    yield from map(AirbyteEntrypoint.airbyte_message_to_string, self.read(source_spec, config, config_catalog, state))\n  File \"/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py\", line 165, in read\n    for message in self.source.read(self.logger, config, catalog, state):\n  File \"/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py\", line 177, in read\n    raise AirbyteTracedException(message=error_message, failure_type=FailureType.config_error)\nairbyte_cdk.utils.traced_exception.AirbyteTracedException: None\n",
  "timestamp" : 1717453364574
}, {
  "failureOrigin" : "source",
  "internalMessage" : "Source process exited with non-zero exit code 1",
  "externalMessage" : "Something went wrong within the source connector",
  "metadata" : {
    "attemptNumber" : 4,
    "jobId" : 55473,
    "connector_command" : "read"
  },
  "stacktrace" : "io.airbyte.workers.internal.exception.SourceException: Source process exited with non-zero exit code 1\n\tat io.airbyte.workers.general.BufferedReplicationWorker.readFromSource(BufferedReplicationWorker.java:378)\n\tat io.airbyte.workers.general.BufferedReplicationWorker.lambda$runAsyncWithHeartbeatCheck$3(BufferedReplicationWorker.java:242)\n\tat java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)\n\tat java.base/java.lang.Thread.run(Thread.java:1583)\n",
  "timestamp" : 1717453364920
} ]
2024-06-03 22:22:45 platform > 
2024-06-03 22:22:45 platform > ----- END REPLICATION -----
2024-06-03 22:22:45 platform > 
2024-06-03 22:22:45 platform > Retry State: RetryManager(completeFailureBackoffPolicy=BackoffPolicy(minInterval=PT10S, maxInterval=PT30M, base=3), partialFailureBackoffPolicy=null, successiveCompleteFailureLimit=5, totalCompleteFailureLimit=10, successivePartialFailureLimit=1000, totalPartialFailureLimit=10, successiveCompleteFailures=5, totalCompleteFailures=5, successivePartialFailures=0, totalPartialFailures=0)
 Backoff before next attempt: 13 minutes 30 seconds
2024-06-03 22:22:45 platform > Failing job: 55473, reason: Job failed after too many retries for connection 5a1efbc5-60c1-4c0f-b767-bb5fec75fc91
```
![image](https://github.com/airbytehq/airbyte/assets/84840546/29228e07-4c53-4e47-b745-3b37555cbe87)

**Comment by tybernstein** [comment]
@khoadaniel Thank you for sharing. It appears that you need to refresh and update the schema for the connection. There may be a pop-up box prompting you to run a clear/reset after saving the changes to the schema, you can uncheck that box if it appears. Try running another sync with the new schema and hopefully that will do the trick!

**Comment by maxi297** [comment]
Since the error is the same, there are two possibilities:
* They haven’t properly upgraded to 3.1.0
* They have custom streams that is using the field cost_per_conversion_lead and they haven’t updated that

Based on our internal reporting, we think the former might be the case for you. Can you make sure you have upgraded the connector properly? Once this is done, you should see in the logs something like `Attempting to start pod = source-facebook-marketing-read-<autogenerated> for airbyte/source-facebook-marketing:3.1.0`

**Comment by maxi297** [comment]
Note for everyone: we have confirmed that this change does not require a reset of the data in the destination if you are using destination v2. We have therefore updated our migration guide. If you have any issue regarding that, let us know!

**Comment by khoadaniel** [comment]
Hi @maxi297 ,

Confirmed that it worked for me without resetting the streams.

**Comment by marcosmarxm** [comment]
@maxi297 can we closed this? What is the PR solving the issue?
