### ISSUE TITLE
[source-MySQL] incremental append behavies different on first run than other runs

### ISSUE THREAD

**Issue by pedrohsroque** [airbytehq/airbyte#43327]
### Connector Name

source-mysql

### Connector Version

3.4.10

### What step the error happened?

Other

### Relevant information

We are replication data from a MySQL database in another timezone using incremental append dedup mode to Snowflake. On the first run (which pulls the entire data) we observed that the timezone for the datetime columns is the same as the original database, but on subsequent runs, it became GMT-0, so now we have part of the data in one timezone and another part in GMT-0, and over time new records are GMT-0, updated records GMT-0 and remaining records from first run are in the original timezone.

When running full refresh, we observed the original timezone for all runs.

![image](https://github.com/user-attachments/assets/36cfdecb-fddb-4af8-8bbc-1f5fb77367b2)

I found similar issues, but all were closed with no apparent solution.

### Contribute

- [ ] Yes, I want to contribute

**Comment by mekedron** [comment]
The difference also with the numeric columns as it's mentioned in this issue:
https://github.com/airbytehq/airbyte/issues/38470#issuecomment-2421964712

**Comment by mekedron** [comment]
Seems like this issue is fixed in the latest `source-mysql` connector

**Comment by jordibeunk1** [comment]
This issue is still present for me on Airbyte 1.4.0 when syncing date from MySQL to Snowflake using incremental append deduped mode (CDC).

source-mysql: 3.11.0
destination-snowflake: 3.15.4

Are there any updates on this issue?

**Comment by iafydsttta** [comment]
> Seems like this issue is fixed in the latest source-mysql connector

Not for me.

**Comment by iafydsttta** [comment]
Definetly not fixed.
