### ISSUE TITLE
[source klaviyo] Missing fields latest release

### ISSUE THREAD

**Issue by gwenhoogeboom** [airbytehq/airbyte#54174]
### Connector Name

source-klaviyo

### Connector Version

2.13.0

### What step the error happened?

Other

### Relevant information

Since the latest version of the Klaviyo source it seems that fields are missing from the events stream, even though no breaking changes are identified in the pull request: https://github.com/airbytehq/airbyte/pull/51551.

Previously, the we could extract the following: attributes['event_properties']['$attribution']. It seems that $attribution is now removed. I do see some change in the source code to extract this data, I see that the 'include' in the api request now includes 'attributions' as well, however, I do not see this data in the schema.

```
retriever:
      $ref: "#/definitions/base_retriever"
      requester:
        $ref: "#/definitions/requester"
        request_parameters:
          "fields[metric]": "name,created,updated,integration"
          "include": "metric,attributions"
          "filter": "greater-or-equal({{ parameters.cursor_field }},{{ stream_interval.start_time }}),less-or-equal({{ parameters.cursor_field }},{{ stream_interval.end_time }})"
          "sort": "{{ parameters.cursor_field }}"
```

### Relevant log output

```shell

```

### Contribute

- [ ] Yes, I want to contribute

**Comment by darynaishchenko** [comment]
hi, @gwenhoogeboom! I have merged pr that adds `event_properties` to request options. Feel free to re-open this issue if the fix was not helpful. Thanks!

**Comment by tuday2** [comment]
I am still seeing this issue where the data is not benig returned. If I query the API directly i get the "included": block that has the attribution data.... Airbyte is not getting it even with the changes made yesterday

**Comment by tuday2** [comment]
Here is what the correct block looks like (i anonymized the record) , Airbyte is missing everything in the "included" block :

`{
  "data": {
    "type": "event",
    "id": "xxx",
    "attributes": {
      "timestamp": 1739720612,
      "event_properties": {
        "event_id": "rrreventit",
        "order_value": 100.00,
        "OrderId": "orderid",
        "Tax": 6.93,
        "Shipping": 0,
        "ItemTotal": 99.99,
        "Discount": 0,
        "OrderTotal": 100.00,
        "OrderStatus": "Pending Fulfillment",
        "Promotion": "",
        "BillingAddress": {
        },
        "ShippingAddress": {
        },
        "$event_id": "hhheventid",
        "$value": 161.00
      },
      "datetime": "2025-02-16T15:43:32+00:00",
      "uuid": "uuid-uuid-uuid-uuid-uuid"
    },
    "relationships": {
      "profile": {
        "data": {
          "type": "profile",
          "id": "rrrprofileid"
        },
        "links": {
          "self": "https://a.klaviyo.com/api/events/xxx/relationships/profile/",
          "related": "https://a.klaviyo.com/api/events/xxx/profile/"
        }
      },
      "metric": {
        "data": {
          "type": "metric",
          "id": "zzzmetric"
        },
        "links": {
          "self": "https://a.klaviyo.com/api/events/xxx/relationships/metric/",
          "related": "https://a.klaviyo.com/api/events/xxx/metric/"
        }
      },
      "attributions": {
        "data": [
          {
            "type": "attribution",
            "id": "xxx"
          }
        ]
      }
    },
    "links": {
      "self": "https://a.klaviyo.com/api/events/xxx
      /"
    }
  },
  "included": [
    {
      "type": "attribution",
      "id": "xxx",
      "attributes": {},
      "relationships": {
        "event": {
          "data": {
            "type": "event",
            "id": "xxx"
          }
        },
        "attributed-event": {
          "data": {
            "type": "event",
            "id": "yyy"
          }
        },
        "campaign": {
          "data": {
            "type": "campaign",
            "id": "234234234234"
          }
        }
      },
      "links": {
        "self": null
      }
    }
  ],
  "links": {
    "self": "https://a.klaviyo.com/api/events/xxx?include=attributions"
  }
}`
