### ISSUE TITLE
--insecure-cookies is ignored in airbyte 1.6.2 with abctl version: v0.26.0

### ISSUE THREAD

**Issue by ibrentlam** [airbytehq/airbyte#61586]
### What happened?

used abctl as:
/usr/local/bin/abctl local install --verbose --insecure-cookies --low-resource-mode --no-browser
but could not log in, got the usual "your credentials were correct, but airbyte is not configured for insecure cookies"

### What did you expect to happen?

I expected to be able to log in as in previous releases 

### Abctl Version

<details>

```console
$ abctl version
# paste output here
version: v0.26.0
```

</details>

### Docker Version

<details>

```console
$ docker version
# paste output here
Client: Docker Engine - Community
 Version:           28.2.2
 API version:       1.50
 Go version:        go1.24.3
 Git commit:        e6534b4
 Built:             Fri May 30 12:07:28 2025
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          28.2.2
  API version:      1.50 (minimum version 1.24)
  Go version:       go1.24.3
  Git commit:       45873be
  Built:            Fri May 30 12:07:28 2025
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.27
  GitCommit:        05044ec0a9a75232cad458027ca83437aae3f4da
 runc:
  Version:          1.2.5
  GitCommit:        v1.2.5-0-g59923ef
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

</details>

### OS Version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here

# On Mac:
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
PRETTY_NAME="Ubuntu 22.04.5 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.5 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

</details>

**Comment by aldo-roman** [comment]
Can confirm. I just ran into the same issue.

As a workaround, I had to disable insecure cookies via CLI

https://docs.airbyte.com/platform/deploying-airbyte/integrations/authentication#disabling-secure-cookies

**Comment by razzeee** [comment]
Downgrading to v0.25.0 allows this to work

**Comment by marcosmarxm** [comment]
Thanks for reporting the problem. I escalated it to the deployment team to fix it.

**Comment by razzeee** [comment]
From the changelog, this doesn't seem to have made it into 0.28.0?
https://github.com/airbytehq/abctl/releases

**Comment by razzeee** [comment]
Yeah, just tried with 0.28.0 - it's still unfixed

**Comment by bernielomax** [comment]
Hi folks, this should be fixed in Abctl `v0.29.0`. Please give it a try.

**Comment by User24081** [comment]
i've same problem in 0.30.0 ((
I'm in training and I'm not very good at everything. I have a virtual machine in the cloud where I am trying to set up airbyte and everything was successful for another week, but now with the upgrade to version 30, the --insecure-cookies key is not helping. my virtual machine doesn't have a hostname, just an IP address.

**Comment by rara010** [comment]
Confirming the issue, it is still not resolved as just --insecure-cookies flag does not enable logging

**Comment by atuldataarch** [comment]
still facing an issue , very time consuming process, earlier docker images was better to work with  abctl version tried v0.30.0
v0.30.1

**Comment by razzeee** [comment]
> Hi folks, this should be fixed in Abctl `v0.29.0`. Please give it a try.

this version fixed it for us - but I havent tried newer builds

**Comment by rara010** [comment]
> > Hi folks, this should be fixed in Abctl `v0.29.0`. Please give it a try.
> 
> this version fixed it for us - but I havent tried newer builds

I was installing on 0.30.0 with no success, i had to use values.yaml 

```

global:
  auth:
    cookieSecureSetting: "false"
    security:
      cookieSecureSetting: "false"

server:
  extraEnv:
    - name: AB_COOKIE_SECURE
      value: "false"
    - name: AB_COOKIE_SAME_SITE
      value: "Lax"
```

**Comment by razzeee** [comment]
> > > Hi folks, this should be fixed in Abctl `v0.29.0`. Please give it a try.
> > 
> > 
> > this version fixed it for us - but I havent tried newer builds
> 
> I was installing on 0.30.0 with no success, i had to use values.yaml
> 
> ```
> 
> global:
>   auth:
>     cookieSecureSetting: "false"
>     security:
>       cookieSecureSetting: "false"
> 
> server:
>   extraEnv:
>     - name: AB_COOKIE_SECURE
>       value: "false"
>     - name: AB_COOKIE_SAME_SITE
>       value: "Lax"
> ```

you should probably use 0.30.1 - which sounds like it fixes that

**Comment by GabrielLins64** [comment]
Hi, @razzeee , I'm using from abctl v0.30.1. It wasn't solved yet.

Command:

```bash
abctl local install \
    --secret ./airbyte/secret.yaml \
    --values ./airbyte/values.yaml \
    --low-resource-mode \
    --insecure-cookies \
    --verbose
```

@rara010 solution worked for me with this `values.yaml`:

```yml
global:
  auth:
    enabled: true
    cookieSecureSetting: "false"
    security:
      cookieSecureSetting: "false"
    instanceAdmin:
      secretName: "airbyte-config-secrets"
      firstName: "FN"
      lastName:  "LN"
      emailSecretName: "instance-admin-email"
      passwordSecretName: "instance-admin-password"

server:
  extraEnv:
    - name: AB_COOKIE_SECURE
      value: "false"
    - name: AB_COOKIE_SAME_SITE
      value: "Lax"
```

**Comment by zafazmii** [comment]
@GabrielLins64 thank you! your solution worked for me :)

**Comment by fighting-u** [comment]
abctl v0.30.1 don't solved yet.
v0.29.0 can make it.

**Comment by ian-at-airbyte** [comment]
If this still isn't working for you, is there any chance you can provide a bit more info about how your environment works, where/which OS you're deploying to, if you're using Oauth, etc.? I'd love if we could get this sorted out. Any more information would help us isolate the issue. Thanks!
