### ISSUE TITLE
Refresh in UI causing error

### ISSUE THREAD

**Issue by matheusnd** [airbytehq/airbyte#65070]
### Helm Chart Version

1.8.0

### What step the error happened?

Other

### Relevant information

When I try to refresh my UI I get the following error:

```
{"message":"Internal Server Error: not yet implemented","exceptionClassName":"java.lang.UnsupportedOperationException","exceptionStack":[],"rootCauseExceptionStack":[]}
```

This error always happens after refreshing the page.

### Relevant log output

```shell
2025-08-18 13:43:53,021 [default-nioEventLoopGroup-2-5]	ERROR	i.a.c.s.e.h.UncaughtExceptionHandler(handle):33 - Uncaught exception
java.lang.UnsupportedOperationException: not yet implemented
	at io.micronaut.http.client.netty.NettyClientHttpRequest.getCookies(NettyClientHttpRequest.java:170)
	at io.micronaut.security.token.cookie.CookieTokenReader.findToken(CookieTokenReader.java:58)
	at io.micronaut.security.token.cookie.CookieTokenReader.findToken(CookieTokenReader.java:34)
	at io.micronaut.security.token.reader.DefaultTokenResolver.lambda$resolveTokens$0(DefaultTokenResolver.java:69)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
	at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
	at io.micronaut.security.token.reader.DefaultTokenResolver.resolveTokens(DefaultTokenResolver.java:79)
	at io.micronaut.security.token.reader.DefaultTokenResolver.resolveTokens(DefaultTokenResolver.java:38)
	at io.micronaut.security.token.TokenAuthenticationFetcher.fetchAuthentication(TokenAuthenticationFetcher.java:134)
	at io.micronaut.security.token.TokenAuthenticationFetcher.fetchAuthentication(TokenAuthenticationFetcher.java:50)
	at io.micronaut.security.filters.SecurityFilter.lambda$doFilter$0(SecurityFilter.java:110)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:388)
	at reactor.core.publisher.FluxIterable$IterableSubscription.slowPath(FluxIterable.java:335)
	at reactor.core.publisher.FluxIterable$IterableSubscription.request(FluxIterable.java:294)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.onSubscribe(FluxFlatMap.java:373)
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:201)
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:83)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4576)
	at io.micronaut.core.async.propagation.ReactivePropagation$1.subscribe(ReactivePropagation.java:72)
	at io.micronaut.core.async.propagation.ReactivePropagation$1.subscribe(ReactivePropagation.java:79)
	at reactor.core.publisher.MonoFromPublisher.subscribe(MonoFromPublisher.java:64)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4576)
	at io.micronaut.core.async.publisher.Publishers.lambda$map$3(Publishers.java:264)
	at io.micronaut.core.async.propagation.ReactivePropagation.lambda$propagate$0(ReactivePropagation.java:54)
	at reactor.core.publisher.MonoFromPublisher.subscribe(MonoFromPublisher.java:64)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:76)
	at io.micronaut.http.reactive.execution.ReactorExecutionFlowImpl.onComplete(ReactorExecutionFlowImpl.java:235)
	at io.micronaut.http.server.netty.NettyRequestLifecycle.handleNormal(NettyRequestLifecycle.java:107)
	at io.micronaut.http.server.netty.RoutingInBoundHandler.accept(RoutingInBoundHandler.java:205)
	at io.micronaut.http.server.netty.websocket.NettyServerWebSocketUpgradeHandler.accept(NettyServerWebSocketUpgradeHandler.java:156)
	at io.micronaut.http.server.netty.handler.PipeliningServerHandler$MessageInboundHandler.read(PipeliningServerHandler.java:437)
	at io.micronaut.http.server.netty.handler.PipeliningServerHandler.channelRead(PipeliningServerHandler.java:228)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:356)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
	at io.netty.handler.codec.http.websocketx.extensions.WebSocketServerExtensionHandler.onHttpRequestChannelRead(WebSocketServerExtensionHandler.java:158)
	at io.netty.handler.codec.http.websocketx.extensions.WebSocketServerExtensionHandler.channelRead(WebSocketServerExtensionHandler.java:85)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:354)
	at io.airbyte.commons.server.support.AuthorizationServerHandler.channelRead(AuthorizationServerHandler.kt:36)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:354)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:434)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:324)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:249)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:354)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:293)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:354)
	at io.airbyte.commons.server.support.AuthorizationServerHandler.channelRead(AuthorizationServerHandler.kt:36)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:354)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:107)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:356)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:356)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1429)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:918)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:167)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.handle(AbstractNioChannel.java:445)
	at io.netty.channel.nio.NioIoHandler$DefaultNioRegistration.handle(NioIoHandler.java:381)
	at io.netty.channel.nio.NioIoHandler.processSelectedKey(NioIoHandler.java:575)
	at io.netty.channel.nio.NioIoHandler.processSelectedKeysOptimized(NioIoHandler.java:550)
	at io.netty.channel.nio.NioIoHandler.processSelectedKeys(NioIoHandler.java:491)
	at io.netty.channel.nio.NioIoHandler.run(NioIoHandler.java:468)
	at io.netty.channel.SingleThreadIoEventLoop.runIo(SingleThreadIoEventLoop.java:207)
	at io.netty.channel.SingleThreadIoEventLoop.run(SingleThreadIoEventLoop.java:178)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:1073)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by yyassif** [comment]
We're experiencing the same error with versions `1.8.0` and `1.7.1`.

```
{
  "message": "Internal Server Error: not yet implemented",
  "exceptionClassName": "java.lang.UnsupportedOperationException",
  "exceptionStack": [],
  "rootCauseExceptionStack": []
}
```

Any updates on when is this gonna be patched? is it an authenticate issue, or an Abstracted / Unimplemented authentication method ?? I am just making assumptions here.

Hope this resolves soon.

**Comment by runawaydevil** [comment]
Same here, someone found an solution?

**Comment by runawaydevil** [comment]
Same problem here.

**Comment by Noah1989** [comment]
Same here during Google authentication, when trying to add a connector.

**Comment by tomredlev-as** [comment]
Same here when we migrated our ingress to use the server service instead of the webapp on `1.7.0` and `1.8.0` helm charts

**Comment by tomdarmon-appstack** [comment]
Same here, this happens every time I refresh. If I go back to the homepage I can navigate again, until the next refresh / change of workspace.

**Comment by ng-shravan** [comment]
Same problem here, Can anyone help for solution please?

**Comment by farhan-helmy** [comment]
same here

**Comment by cawdry-dev** [comment]
same here, also getting auth errors on the api 

POST api/public/v1/applications/token

```JSON
{
    "message": "Bad Request",
    "_links": {
        "self": {
            "href": "/api/public/v1/applications/token",
            "templated": false
        }
    },
    "_embedded": {
        "errors": [
            {
                "message": "Invalid client id or token",
                "_links": {},
                "_embedded": {}
            }
        ]
    }
}
```
Everything was working fine before the last update.

**Comment by yuvaraj91** [comment]
Same here, helm deployment on EKS

**Comment by neguezaymen** [comment]
Same problem,on refresh and oauth connectors :/

**Comment by runawaydevil** [comment]
naturally, it’s a bug and we’ll have to wait for fixes. i can’t sync my data anymore, so i rolled back and i’m using an older version that seems stable for now.

**Comment by neguezaymen** [comment]
which version are you using for airbyte and abctl ? thx

**Comment by femorgon** [comment]
Same here. Airbyte version v1.8.1 and abctl v0.30.1

**Comment by jonathandsantiago** [comment]
I'm experiencing a critical bug with abctl v0.30.1 that prevents the web interface from loading properly.
Error Details:

Version: abctl v0.30.1
Environment: macOS with Docker Desktop
Issue: Web interface returns HTTP 503 and throws UnsupportedOperationException: not yet implemented in the CookieTokenReader.findToken() method

Error Stack Trace:
java.lang.UnsupportedOperationException: not yet implemented
at io.micronaut.http.client.netty.NettyClientHttpRequest.getCookies(NettyClientHttpRequest.java:170)
at io.micronaut.security.token.cookie.CookieTokenReader.findToken(CookieTokenReader.java:58)
at io.airbyte.commons.server.support.AuthorizationServerHandler.channelRead(AuthorizationServerHandler.kt:36)

**Comment by hanslemm** [comment]
Since Airbyte is not accepting contributions at [Airbyte Platform Repo](https://github.com/airbytehq/airbyte-platform/tree/main), I had to create my [fork](https://github.com/hanslemm/airbyte-platform) and build a custom image for `airbyte-server` pod.

The issue is in the `WebappFilter.kt`. What my [changes](https://github.com/airbytehq/airbyte-platform/compare/main...hanslemm:airbyte-platform:main?expand=1)(check file changes tab) does:
- Before: HttpRequest.create(...) returned a Netty client request; when Micronaut Security’s CookieTokenReader runs on SPA refresh (where copy() is used), it calls getCookies() and hits UnsupportedOperationException.
- Now: SimpleHttpRequest implements server-side request behaviors (cookies parsed via headers), so CookieTokenReader can read cookies without error. The rest of WebappFilter (CSP/Last-Modified and redirects) is unchanged.

My custom image with the fix is [here](https://hub.docker.com/repository/docker/hlemm/airbyte-server/tags) while Airbyte doesn't patch it.

**Comment by sheinbergon** [comment]
@marcosmarxm Any chance you'll be fixing this issue?

**Comment by yuvaraj91** [comment]
This issue is still present on v1.8.2 release

**Comment by matheusnd** [comment]
It is not possible to simple downgrade the Airbyte to an older version. On my case it was required to deploy a new instance and migrate the connections manually. 

We are now using the version 1.5.1.

**Comment by iulianapostol-ozone** [comment]
@matheusnd  yeah that's becasue of the flyway migrations from >= 1.8.0, they apply the new schema and old binaries can't use it anymore.

**Comment by iulianapostol-ozone** [comment]
@hanslemm you're a life saver mate, thank you

**Comment by mombrea** [comment]
Same issue here on Airbyte 1.8.2 and abctl v0.30.1

**Comment by Ricardonacif** [comment]
+1

**Comment by theviktor** [comment]
Same issue on V1.8.2 abctl installed, while this only happens on refresh, and we can just go back to the root url /, it's a bit annoying, hope they fix this on V1.8.3

**Comment by mombrea** [comment]
> Same issue on V1.8.2 abctl installed, while this only happens on refresh, and we can just go back to the root url /, it's a bit annoying, hope they fix this on V1.8.3

I'd like to point out this also impacts any connector that requires oauth as the page will refresh to form the connection and fail.

**Comment by tomdarmon-appstack** [comment]
This is a big problem that barely makes Airbyte usable. In my case it was after an upgrade. Do fresh deployments have the same issue?

Can an Airbyte member push this up the priority list somehow?

**Comment by sheinbergon** [comment]
@marcosmarxm

**Comment by Wiselawai** [comment]
Same issue

**Comment by LucLagrange** [comment]
Same issue here

**Comment by billy-sightline** [comment]
Same issue

**Comment by Hesperide** [comment]
Thank you to everyone for raising this. The Airbyte team is working on a fix. Expect a new patch to version 1.8 in the next week with a fix to the issue. This should resolve any errors when refreshing the Airbyte UI, as well as errors when configuring OAuth for a new or existing connector.

**Comment by Pareetoshd** [comment]
Hi @Hesperide @marcosmarxm 
still facing same issue while accessing Ui 

{
  "message": "Internal Server Error: not yet implemented",
  "exceptionClassName": "java.lang.UnsupportedOperationException",
  "exceptionStack": [],
  "rootCauseExceptionStack": []
}

**Comment by unfrgivn** [comment]
@matheusnd this appears fixed in 1.8.3 that was just released. I haven't tested extensively, but the frontend seems to work as normal.

**Comment by nicolas-wyrwa-celebrate** [comment]
Will this also be fixed for 1.7?

**Comment by Hesperide** [comment]
Thank you everyone for your patience. This is fixed in as of 1.8.3. The fix was also pushed to 1.7.6. Let us know if you encounter any more issues.

**Comment by suhl79** [comment]
It looks the issue is still there in 2.0.0 both self-hosted and cloud.
