### ISSUE TITLE
Hubspot Connctor - Change history tracking for properties

### ISSUE THREAD

**Issue by rupakpatel** [airbytehq/airbyte#7554]
## Tell us about the problem you're trying to solve
Be able to get the timestamps of different values within properties on a contact as they change.

## Describe the solution you’d like
A contact history table which has the contact id, property name, value, and the timestamp of when that value was assigned.

## Describe the alternative you’ve considered or used
Currently use a python script that uses the hubspot api which grabs the JSON response for an individual contact and then extracts the value history of each property

## Additional context
There are a few things to consider:
* It seems with the hubspot api the history can only be obtained by calling one contact at a time which can be end up taking some time if there are thousands or 100s of thousands plus contacts
* There doesn't appear to be anyway of seeing if a new value of a property has been updated for a contact without calling on each individual contact which means essentially for every refresh it ends up being a full refresh and cannot do incrementals.

## Are you willing to submit a PR?

Unfortunately I don't have the skills, all I can do is some basic python to get me by and SQL.

**Comment by tinomerl** [comment]
@sherifnada i'm currently locally working and testing the stream described in #6493 and also need the stream described in here. would be willing to start working on this too.

**Comment by wallies** [comment]
Tested this on 0.35.11 and 0.35.14 airbyte. Both syncing from hubspot to bigquery. I see it syncing property history since 2020 but it times out and retries after some chunks. It then syncs successfully  but nothing ends up in bigquery. I would think it would have a lot of data

**Comment by martinibach** [comment]
I also can't retrieve any data from the endpoint in my testing environment. I just changed values on a deal to test it and no data is pulled. I'm running on 0.35.17-alpha on AWS EKS.

**Comment by marcosmarxm** [comment]
@martinibach did you test the latest version of Hubspot connector?

**Comment by garygcd** [comment]
I am also not getting any data from the property_history stream; hangs after tmp tables are created.
Airbyte v0.39.13-alpha on Mac localhost.

Are others seeing success with this stream?

**Comment by sherifnada** [comment]
cc @misteryeo for prioritization into the team's sprint

**Comment by wallies** [comment]
Retested on 0.39.27 and it works but normalization fails. Below is error log. The other thing that does not appear to work is property history for custom fields. We can only see hubspot fields. We get the custom fields in the contacts stream but not the history tracking.

```
	at io.airbyte.workers.general.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:60) ~[io.airbyte-airbyte-workers-0.39.5-alpha.jar:?]
	at io.airbyte.workers.general.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:21) ~[io.airbyte-airbyte-workers-0.39.5-alpha.jar:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:158) ~[io.airbyte-airbyte-workers-0.39.5-alpha.jar:?]
	... 1 more
	Suppressed: io.airbyte.workers.exception.WorkerException: Normalization process wasn't successful
		at io.airbyte.workers.normalization.DefaultNormalizationRunner.close(DefaultNormalizationRunner.java:162) ~[io.airbyte-airbyte-workers-0.39.5-alpha.jar:?]
		at io.airbyte.workers.general.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:48) ~[io.airbyte-airbyte-workers-0.39.5-alpha.jar:?]
		at io.airbyte.workers.general.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:21) ~[io.airbyte-airbyte-workers-0.39.5-alpha.jar:?]
		at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:158) ~[io.airbyte-airbyte-workers-0.39.5-alpha.jar:?]
		at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by marcosmarxm** [comment]
@wallies please post complete log file. The snippet you pasted doens't give the cause of failure.

**Comment by wallies** [comment]
> @wallies please post complete log file. The snippet you pasted doens't give the cause of failure.

attached log. Removed somethings that could be sensitive and the retries

**Comment by wallies** [comment]
@marcosmarxm Ive run it again and i see these errors. The other big issue is it isnt pulling across custom fields for property history whether i normalize it or not

```
661233 schema validation errors found for stream property_history. Error message: Record schema validation failed for property_history. Expected schema: {"type":["null","object"],"$schema":"http://json-schema.org/draft-07/schema#","properties":{"vid":{"type":["null","integer"]},"value":{"type":["null","string"]},"property":{"type":["null","string"]},"selected":{"type":["null","boolean"]},"source-id":{"type":["null","string"]},"timestamp":{"type":["null","string"],"format":"date-time"},"source-type":{"type":["null","string"]},"source-label":{"type":["null","string"]},"updated-by-user-id":{"type":["null","integer"]}}}
```

```
2022-06-20 22:20:22 [42mnormalization[0m > 22:20:09.991348 [debug] [Thread-7  ]: BigQuery adapter: Retry attempt 1 of 3 after error: BadRequest("Invalid timestamp: '1655763557534'")
2022-06-20 22:20:22 [42mnormalization[0m > 22:20:11.471549 [debug] [Thread-7  ]: BigQuery adapter: Retry attempt 2 of 3 after error: BadRequest("Invalid timestamp: '1655763557534'")
2022-06-20 22:20:22 [42mnormalization[0m > 22:20:13.032875 [debug] [Thread-7  ]: BigQuery adapter: Retry attempt 3 of 3 after error: BadRequest("Invalid timestamp: '1611276891062'")
```

**Comment by davydov-d** [comment]
hey @wallies which version of the connector are you using? the custom fields issue has been fixed in 0.1.68.
To fix the normalization issue, please refresh the schema

**Comment by davydov-d** [comment]
btw, I have just published version 0.1.73 - the incremental mode is not supported for this stream anymore, but full_refresh should work even more smoothly

**Comment by wallies** [comment]
Hi @davydov-d ive just tested with 0.1.74 with full refresh and the normalization works, cheers. Custom fields are still not coming through in the history stream though

**Comment by davydov-d** [comment]
@wallies could you please share the log file?

I've just added a new custom property to the Contact entity within the test account to verify and it works as expected..

**Comment by wallies** [comment]
@davydov-d custom properties are coming through now but we had to recreate the source and destination and connection, which isnt ideal everytime their is a fix
